# Generated by Django 5.0.7 on 2026-09-09 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vent_auth', '0080_organization_is_premium_organization_premium_note_and_more'),
        ('vent_tournament', '0051_prizeschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=160, null=True, unique=True)),
                ('kind', models.CharField(choices=[('service', 'Offering a skill'), ('swap', 'Trading or exchanging'), ('sale', 'Selling')], max_length=10)),
                ('category', models.CharField(choices=[('coaching', 'Coaching'), ('streaming', 'Streaming'), ('content', 'Content creation'), ('design', 'Graphic design'), ('merchandise', 'Merchandise'), ('in_game', 'In-game items, skins or accounts'), ('anime', 'Anime and manga items')], max_length=20)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.IntegerField(default=0)),
                ('price_kind', models.CharField(blank=True, default='', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('available_to', models.DateTimeField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, default='')),
                ('delivery', models.CharField(blank=True, default='', max_length=12)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('offered', models.CharField(blank=True, default='', max_length=200)),
                ('wanted', models.CharField(blank=True, default='', max_length=200)),
                ('trade_value', models.IntegerField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, default='', max_length=10)),
                ('payment_methods', models.CharField(blank=True, default='', max_length=200)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('discount_code', models.CharField(blank=True, default='', max_length=40)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('hoisted_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Not published'), ('active', 'Live'), ('paused', 'Paused by the seller'), ('sold', 'Sold or completed'), ('expired', 'Past its date'), ('removed', 'Taken down')], default='draft', max_length=10)),
                ('bidding', models.BooleanField(default=False)),
                ('bids_close_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('response_time_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('inquiries', models.PositiveIntegerField(default=0)),
                ('completed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='vent_auth.games')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='vent_auth.organization')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='vent_tournament.tournament')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('message', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('open', 'Standing'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('expired', 'The window closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='vent_marketplace.listing')),
            ],
            options={
                'ordering': ['-amount', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='marketplace/')),
                ('caption', models.CharField(blank=True, default='', max_length=140)),
                ('portfolio', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='vent_marketplace.listing')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=40, null=True, unique=True)),
                ('amount', models.IntegerField()),
                ('commission', models.IntegerField(default=0)),
                ('seller_amount', models.IntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('held', 'Held by V-ENT'), ('released', 'Paid to the seller'), ('refunded', 'Returned to the buyer'), ('disputed', 'With an admin'), ('cancelled', 'Called off before delivery')], default='held', max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('hold_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vent_auth.transaction')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='vent_marketplace.listing')),
                ('release_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vent_auth.transaction')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('settled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('body', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vent_marketplace.listing')),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='vent_marketplace.purchase')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=140)),
                ('category', models.CharField(blank=True, default='', max_length=20)),
                ('kind', models.CharField(blank=True, default='', max_length=10)),
                ('max_price', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', '-created_at'], name='vent_market_status_5e894e_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['kind', 'category'], name='vent_market_kind_00bfcf_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['seller', 'status'], name='vent_market_seller__a6cdc4_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['listing', 'status'], name='vent_market_listing_1d9104_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['status', '-created_at'], name='vent_market_status_691bed_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['buyer', '-created_at'], name='vent_market_buyer_i_b25b61_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['seller', '-created_at'], name='vent_market_seller__ba727a_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['seller', '-created_at'], name='vent_market_seller__009db4_idx'),
        ),
    ]
