# Generated by Django 5.2.17 on 2026-09-30 01:39

import django.core.validators
import vent_auth.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmedia',
            name='file',
            field=models.FileField(upload_to=vent_auth.uploads.OpaqueName('marketplace/'), validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'gif', 'mp4', 'webm', 'mov'])]),
        ),
    ]
