# Generated by Django 4.2.6 on 2024-06-06 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vent_auth", "0002_games_remove_users_full_name_users_user_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournaments",
            fields=[
                ("tournament_id", models.AutoField(primary_key=True, serialize=False)),
                ("tournament_name", models.CharField(max_length=148)),
                ("tournament_desc", models.TextField()),
                ("tournament_type", models.CharField(max_length=5)),
                ("tournament_registration_date", models.DateField()),
                ("tournament_checkin_date", models.DateField()),
                (
                    "tournament_creator_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament_game_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vent_auth.games",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegisteredTeams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_date", models.DateField()),
                (
                    "team_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vent_auth.teams",
                    ),
                ),
                (
                    "tournament_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vent_tournament.tournaments",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheckInTeams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in_date", models.DateField()),
                (
                    "team_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vent_auth.teams",
                    ),
                ),
                (
                    "tournament_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vent_tournament.tournaments",
                    ),
                ),
            ],
        ),
    ]
