# Generated by Django 4.2.6 on 2024-06-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vent_tournament", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournaments",
            name="tournament_creation_date",
            field=models.DateField(default="22222"),
            preserve_default=False,
        ),
    ]
