# Generated by Django 4.2.6 on 2024-06-06 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vent_tournament", "0002_tournaments_tournament_creation_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournaments",
            name="tournament_creation_date",
        ),
    ]
