# Generated by Django 4.2.6 on 2024-06-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vent_tournament", "0003_remove_tournaments_tournament_creation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournaments",
            name="tournament_creation_date",
            field=models.DateField(default="2024-01-02"),
            preserve_default=False,
        ),
    ]
