# Generated by Django 5.0.7 on 2024-08-20 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0007_alter_orgwallet_org_wallet_id_and_more'),
        ('vent_tournament', '0004_tournaments_tournament_creation_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournaments',
            name='tournament_creator_id',
        ),
        migrations.RemoveField(
            model_name='tournaments',
            name='tournament_game_type',
        ),
        migrations.RemoveField(
            model_name='registeredteams',
            name='registration_date',
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_id', models.AutoField(primary_key=True, serialize=False)),
                ('tournament_name', models.CharField(max_length=148)),
                ('tournament_desc', models.TextField()),
                ('tournament_creation_date', models.DateField()),
                ('tournament_type', models.CharField(max_length=5)),
                ('tournament_registration_date', models.DateField()),
                ('tournament_registration_end_date', models.DateField()),
                ('tournament_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tournaments', to=settings.AUTH_USER_MODEL)),
                ('tournament_game_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='vent_auth.games')),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_check_in_time', models.TimeField()),
                ('match_check_in_date', models.DateField()),
                ('match_check_in_started', models.BooleanField(default=False)),
                ('match_check_in_ended', models.BooleanField(default=False)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='vent_tournament.tournament')),
            ],
        ),
        migrations.AlterField(
            model_name='registeredteams',
            name='tournament_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vent_tournament.tournament'),
        ),
        migrations.CreateModel(
            name='UnconfirmedTeams',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vent_auth.teams')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.DeleteModel(
            name='CheckInTeams',
        ),
        migrations.DeleteModel(
            name='Tournaments',
        ),
    ]
