# Generated by Django 5.0.7 on 2024-10-21 08:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0005_remove_tournaments_tournament_creator_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsor_logos/')),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={},
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='tournament_name',
            new_name='tournament_title',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_creation_date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_creator',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_desc',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_game_type',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_registration_date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_registration_end_date',
        ),
        migrations.AddField(
            model_name='tournament',
            name='bracket_type',
            field=models.CharField(default='Single Elim', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='end_date_and_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='entry_fee',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], default='Paid', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='entry_fee_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='kick_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_number_of_teams',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='min_number_of_teams',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_date_and_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_access',
            field=models.CharField(choices=[('team', 'Team'), ('individual', 'Individual'), ('team_and_individual', 'Team and Individual')], default='Public', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_banner',
            field=models.ImageField(blank=True, null=True, upload_to='tournament_banners/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_logo',
            field=models.ImageField(blank=True, null=True, upload_to='tournament_logos/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('protected', 'Protected')], default='Public', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='twitch_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('online', 'Online'), ('physical', 'Physical'), ('hybrid', 'Hybrid')], max_length=8),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sponsors',
            field=models.ManyToManyField(blank=True, to='vent_tournament.sponsor'),
        ),
        migrations.CreateModel(
            name='TournamentPrizeDistribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('prize', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extras', models.CharField(blank=True, max_length=40)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_distributions', to='vent_tournament.tournament')),
            ],
        ),
    ]
