# Generated by Django 5.0.7 on 2026-03-22 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('vent_auth', '0019_remove_teams_team_privacy_and_more'),
        ('vent_tournament', '0008_tournament_registration_bracket_dispute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('sponsor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sponsor_id_object', models.PositiveIntegerField(null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsor_logos/')),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
        migrations.RemoveConstraint(
            model_name='tournamentregistration',
            name='unique_tournament_team',
        ),
        migrations.RemoveConstraint(
            model_name='tournamentregistration',
            name='unique_tournament_user',
        ),
        migrations.AddField(
            model_name='tournament',
            name='bigolive_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='game_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='interaction_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_type',
            field=models.CharField(choices=[('distributed', 'Distributed'), ('winner_takes_all', 'Winner Takes All'), ('no_prize', 'No Prize')], default='no_prize', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='team_size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tiktok_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vent_auth.games'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vent_auth.organization'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='virtual_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bracketmatch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registeredteams',
            name='tournament_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_teams', to='vent_tournament.tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bracket_type',
            field=models.CharField(default='Single Elimination', max_length=50),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('protected', 'Protected')], default='public', max_length=9),
        ),
        migrations.AlterField(
            model_name='tournamentdispute',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentregistration',
            unique_together={('tournament', 'team'), ('tournament', 'user')},
        ),
        migrations.AddField(
            model_name='sponsors',
            name='sponsor_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='sponsors',
            field=models.ManyToManyField(blank=True, to='vent_tournament.sponsors'),
        ),
    ]
