# Generated by Django 5.0.7 on 2026-07-06 20:44
# Restructured 2026-07-06: prepend a PK column-type reconciliation so this
# migration applies on a freshly-built MySQL database (see block comment below).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _int_pk():
    return models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')


def _big_pk():
    return models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')


class Migration(migrations.Migration):

    dependencies = [
        # Bumped 0020 -> 0022 so vent_auth's Transaction.id INT->BigAutoField alter
        # runs BEFORE PrizePayout.transaction (a BIGINT FK) is created on a fresh DB;
        # otherwise MySQL rejects the FK with error 3780 (BIGINT FK -> INT PK).
        ('vent_auth', '0022_align_wallet_admin_pks_to_bigautofield'),
        ('vent_tournament', '0009_sponsors_delete_sponsor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # -------------------------------------------------------------------
        # PK column-type reconciliation (MUST run before the BigAutoField FKs).
        #
        # Migration 0008 created BracketMatch / TournamentRegistration /
        # TournamentDispute with INT `AutoField` PKs. Migration 0009 then moved
        # those PKs to BigAutoField in STATE ONLY (`database_operations=[]`,
        # because the then-deployed DB already had BIGINT columns). On a freshly
        # built database the columns are therefore still INT while the migration
        # state claims BigAutoField — so the self-referential BigAutoField FKs
        # added below emit BIGINT columns that MySQL refuses to point at INT PKs
        # (error 3780). A plain AlterField(->BigAutoField) here would be a state
        # no-op (state is already BigAutoField) and emit no DDL.
        #
        # Fix: rewind the STATE to AutoField (state-only), then run a REAL
        # AlterField to BigAutoField. Django then performs the INT->BIGINT column
        # change and cascades it to every referencing FK column, dropping and
        # re-adding constraints as needed. On a database whose columns are
        # already BIGINT this simply re-alters BIGINT->BIGINT (harmless).
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField('tournamentregistration', 'id', _int_pk()),
                migrations.AlterField('bracketmatch', 'id', _int_pk()),
                migrations.AlterField('tournamentdispute', 'id', _int_pk()),
            ],
            database_operations=[],
        ),
        migrations.AlterField('tournamentregistration', 'id', _big_pk()),
        migrations.AlterField('bracketmatch', 'id', _big_pk()),
        migrations.AlterField('tournamentdispute', 'id', _big_pk()),

        # -------------------------------------------------------------------
        # Original 0010 schema additions.
        migrations.AddField(
            model_name='bracketmatch',
            name='bracket_side',
            field=models.CharField(choices=[('winners', 'Winners bracket'), ('losers', 'Losers bracket'), ('grand_final', 'Grand final')], default='winners', max_length=12),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='loser_to_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vent_tournament.bracketmatch'),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='loser_to_slot',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='winner_to_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vent_tournament.bracketmatch'),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='winner_to_slot',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='cancelled_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tournament',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='score_confirmation_mode',
            field=models.CharField(choices=[('organizer_only', 'Organizer records results'), ('both_players_confirm', 'Both players confirm'), ('screenshot_required', 'Screenshot required')], default='both_players_confirm', help_text='Who confirms match scores. Chosen by the organizer at creation.', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('registration_open', 'Registration open'), ('registration_closed', 'Registration closed'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', help_text="Lifecycle status. 'draft' mirrors is_draft=True.", max_length=20),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='final_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='seed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bracketmatch',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('pending_opponent_confirm', 'Pending opponent confirm'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('bye', 'Bye')], default='scheduled', max_length=24),
        ),
        migrations.AlterField(
            model_name='tournamentprizedistribution',
            name='prize',
            field=models.DecimalField(decimal_places=2, help_text='Amount in VENT COINS', max_digits=10),
        ),
        migrations.CreateModel(
            name='BracketGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_strategy', models.CharField(choices=[('random', 'Random'), ('ranked', 'Ranked'), ('manual_order', 'Manual order')], default='random', max_length=20)),
                ('seed_payload', models.JSONField(default=dict)),
                ('match_count', models.PositiveIntegerField(default=0)),
                ('rounds_count', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bracket_generations', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bracket_generations', to='vent_tournament.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_p1', models.IntegerField()),
                ('score_p2', models.IntegerField()),
                ('evidence_url', models.CharField(blank=True, max_length=500)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_scores_confirmed', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_submissions', to='vent_tournament.bracketmatch')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_scores_submitted', to=settings.AUTH_USER_MODEL)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='vent_tournament.matchscore')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PrizePayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('amount', models.IntegerField()),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('auto_distributed', models.BooleanField(default=False)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prize_payouts_made', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_payouts', to='vent_tournament.tournament')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vent_auth.transaction')),
                ('winner_registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prize_payouts', to='vent_tournament.tournamentregistration')),
            ],
            options={
                'unique_together': {('tournament', 'position')},
            },
        ),
    ]
