# Generated by Django 5.0.7 on 2026-08-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0012_reconcile_tournament_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='prize_currency',
            field=models.CharField(blank=True, default='VC', max_length=3),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_pool_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_pool_total_vc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tournamentprizedistribution',
            name='amount_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tournamentprizedistribution',
            name='currency',
            field=models.CharField(blank=True, default='VC', max_length=3),
        ),
        migrations.AddField(
            model_name='tournamentprizedistribution',
            name='extras_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tournamentprizedistribution',
            name='extras_prize',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='A bonus in VENT COINS, converted the same way as the prize.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentprizedistribution',
            name='extras',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='tournamentprizedistribution',
            name='prize',
            field=models.DecimalField(decimal_places=2, help_text='Amount in VENT COINS. Always the converted figure - this is what pays out.', max_digits=10),
        ),
    ]
