# Generated by Django 5.0.7 on 2026-08-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0014_tournament_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='forfeited_reason',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
