# Generated by Django 5.0.7 on 2026-08-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0015_tournament_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='check_in_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
