# Generated by Django 5.0.7 on 2026-08-27 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0016_tournament_check_in_closed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_win', models.IntegerField(default=3)),
                ('points_draw', models.IntegerField(default=1)),
                ('points_loss', models.IntegerField(default=0)),
                ('tiebreakers', models.JSONField(blank=True, default=list)),
                ('players_per_team', models.PositiveSmallIntegerField(default=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='league_rules', to='vent_tournament.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TieFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField()),
                ('goals_1', models.IntegerField(default=0)),
                ('goals_2', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('forfeit', 'Forfeit')], default='scheduled', max_length=24)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('player_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tie_fixtures_as_p1', to=settings.AUTH_USER_MODEL)),
                ('player_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tie_fixtures_as_p2', to=settings.AUTH_USER_MODEL)),
                ('tie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='vent_tournament.bracketmatch')),
            ],
            options={
                'ordering': ['tie_id', 'slot'],
            },
        ),
        migrations.AddConstraint(
            model_name='tiefixture',
            constraint=models.UniqueConstraint(fields=('tie', 'slot'), name='one_fixture_per_slot'),
        ),
    ]
