# Generated by Django 5.0.7 on 2026-08-27 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0050_alter_games_options_games_is_active_games_sort_order_and_more'),
        ('vent_tournament', '0017_leaguerules_tiefixture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='vent_auth.gameseries'),
        ),
    ]
