# Generated by Django 5.0.7 on 2026-08-28 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0020_entry_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=60)),
                ('format', models.CharField(max_length=40)),
                ('advances', models.PositiveIntegerField(default=0)),
                ('groups', models.PositiveIntegerField(default=0)),
                ('rules', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete')], default='pending', max_length=20)),
                ('advanced', models.JSONField(blank=True, default=list)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='vent_tournament.tournament')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('tournament', 'order')},
            },
        ),
    ]
