# Generated by Django 5.0.7 on 2026-08-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0021_tournament_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='rules_document',
            field=models.FileField(blank=True, null=True, upload_to='tournament_rules/'),
        ),
    ]
