# Generated by Django 5.0.7 on 2026-08-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0022_tournament_rules_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracketmatch',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='running_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
