# Generated by Django 5.0.7 on 2026-08-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0024_tournamentinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='approve_registrations',
            field=models.BooleanField(default=False),
        ),
    ]
