# Generated by Django 5.0.7 on 2026-08-29 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0025_tournament_approve_registrations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentMVP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField(default=0)),
                ('overridden', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('decided_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mvp_decisions', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mvp_awards', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mvp', to='vent_tournament.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayerStat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=40)),
                ('value', models.FloatField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='vent_tournament.bracketmatch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='vent_tournament.tournamentregistration')),
            ],
            options={
                'ordering': ['match_id', 'player_id', 'key'],
                'unique_together': {('match', 'player', 'key')},
            },
        ),
        migrations.CreateModel(
            name='TournamentMetric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=40)),
                ('weight', models.FloatField(default=1.0)),
                ('position', models.PositiveIntegerField(default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='vent_tournament.tournament')),
            ],
            options={
                'ordering': ['position', 'id'],
                'unique_together': {('tournament', 'key')},
            },
        ),
    ]
