# Generated by Django 5.0.7 on 2026-08-29 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0026_tournamentmvp_matchplayerstat_tournamentmetric'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReminder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('check_in', 'Check in'), ('match', 'Your next match'), ('custom', 'My own message')], default='check_in', max_length=20)),
                ('subject', models.CharField(blank=True, default='', max_length=140)),
                ('body', models.TextField(blank=True, default='', max_length=2000)),
                ('anchor', models.CharField(choices=[('tournament_start', 'The tournament start'), ('check_in_opens', 'Check-in opening'), ('check_in_closes', 'Check-in closing'), ('fixed', 'A time I choose')], default='check_in_opens', max_length=30)),
                ('offset_minutes', models.IntegerField(default=60)),
                ('fixed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('skipped_reason', models.CharField(blank=True, default='', max_length=200)),
                ('people_reached', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_reminders', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reminders', to='vent_tournament.tournament')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
