# Generated by Django 5.0.7 on 2026-08-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0027_scheduledreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='registration_closes_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_opens_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
