# Generated by Django 5.0.7 on 2026-08-29 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0058_conversation_slug'),
        ('vent_tournament', '0028_tournament_registration_closes_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentInvitation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, default='', max_length=280)),
                ('status', models.CharField(choices=[('pending', 'Waiting for an answer'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn by the organiser')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_invitations', to='vent_auth.teams')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='vent_tournament.tournament')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='tournamentinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('tournament', 'user'), name='one_invitation_per_player'),
        ),
        migrations.AddConstraint(
            model_name='tournamentinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('tournament', 'team'), name='one_invitation_per_team'),
        ),
    ]
