# Generated by Django 5.0.7 on 2026-08-29 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0029_tournamentinvitation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentOverlay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to='tournament_overlays/')),
                ('token', models.CharField(db_index=True, max_length=48, unique=True)),
                ('binding', models.CharField(default='none', max_length=20)),
                ('bound_fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_overlays', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlays', to='vent_tournament.tournament')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
