# Generated by Django 5.0.7 on 2026-09-01 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0030_tournamentoverlay'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('token', models.CharField(db_index=True, max_length=48, unique=True)),
                ('status', models.CharField(choices=[('live', 'Live'), ('ended', 'Ended')], default='live', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_sessions', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_sessions', to='vent_tournament.tournament')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastElement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('scorebar', 'Score bar'), ('standings', 'Standings table'), ('lower_third', 'Lower third'), ('player_card', 'Player card'), ('bracket', 'Bracket'), ('ticker', 'Ticker'), ('intro', 'Intro'), ('outro', 'Outro')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='vent_tournament.broadcastsession')),
            ],
            options={
                'ordering': ['kind'],
                'unique_together': {('session', 'kind')},
            },
        ),
    ]
