# Generated by Django 5.0.7 on 2026-09-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0031_broadcastsession_broadcastelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracketmatch',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('pending_opponent_confirm', 'Pending opponent confirm'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('bye', 'Bye'), ('walkover_p1', 'Walkover to the first participant'), ('walkover_p2', 'Walkover to the second participant'), ('cancelled', 'Cancelled')], default='scheduled', max_length=24),
        ),
    ]
