# Generated by Django 5.0.7 on 2026-09-02 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0032_shortlink_tournament_alter_shortlink_event_and_more'),
        ('vent_tournament', '0032_alter_bracketmatch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentoverlay',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overlays', to='vent_event.event'),
        ),
        migrations.AlterField(
            model_name='tournamentoverlay',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overlays', to='vent_tournament.tournament'),
        ),
    ]
