# Generated by Django 5.0.7 on 2026-09-02 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0032_shortlink_tournament_alter_shortlink_event_and_more'),
        ('vent_tournament', '0033_tournamentoverlay_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastsession',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_sessions', to='vent_event.event'),
        ),
        migrations.AlterField(
            model_name='broadcastelement',
            name='kind',
            field=models.CharField(choices=[('scorebar', 'Score bar'), ('standings', 'Standings table'), ('lower_third', 'Lower third'), ('player_card', 'Player card'), ('bracket', 'Bracket'), ('sponsors', 'Sponsor wall'), ('ticker', 'Ticker'), ('intro', 'Intro'), ('outro', 'Outro'), ('now_next', 'Now and next'), ('programme', 'Programme'), ('doors', 'Doors')], max_length=20),
        ),
        migrations.AlterField(
            model_name='broadcastsession',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_sessions', to='vent_tournament.tournament'),
        ),
    ]
