# Generated by Django 5.0.7 on 2026-09-03 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0032_shortlink_tournament_alter_shortlink_event_and_more'),
        ('vent_tournament', '0036_tiefixture_recorded_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastsession',
            name='defaults',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='broadcastelement',
            name='kind',
            field=models.CharField(choices=[('scorebar', 'Score bar'), ('standings', 'Standings table'), ('lower_third', 'Lower third'), ('player_card', 'Player card'), ('bracket', 'Bracket'), ('sponsors', 'Sponsor wall'), ('media', 'Clip or picture'), ('ticker', 'Ticker'), ('intro', 'Intro'), ('outro', 'Outro'), ('now_next', 'Now and next'), ('programme', 'Programme'), ('doors', 'Doors')], max_length=20),
        ),
        migrations.CreateModel(
            name='StudioAsset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('video', 'Video'), ('image', 'Image')], max_length=8)),
                ('name', models.CharField(max_length=140)),
                ('file', models.FileField(upload_to='studio_assets/')),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('team_tag', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studio_assets', to='vent_event.event')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studio_assets', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studio_assets', to='vent_tournament.tournament')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studio_assets_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
