# Generated by Django 5.0.7 on 2026-09-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0037_studio_assets_and_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='studioasset',
            name='slot',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
    ]
