# Generated by Django 5.0.7 on 2026-09-03 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0069_userblock_usermute_userreport'),
        ('vent_tournament', '0038_studio_asset_slot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SquadMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('represents_name', models.CharField(blank=True, default='', max_length=148)),
                ('is_captain', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_captain', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='TournamentSquad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('tag', models.CharField(blank=True, default='', max_length=8)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='squad_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='tournamentinvitation',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddConstraint(
            model_name='tournamentinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('tournament', 'email'), name='one_invitation_per_email'),
        ),
        migrations.AddField(
            model_name='squadmember',
            name='represents_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='squad_representations', to='vent_auth.organization'),
        ),
        migrations.AddField(
            model_name='squadmember',
            name='represents_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='squad_representations', to='vent_auth.teams'),
        ),
        migrations.AddField(
            model_name='squadmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentsquad',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='squads_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentsquad',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='vent_tournament.tournament'),
        ),
        migrations.AddField(
            model_name='squadmember',
            name='squad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='vent_tournament.tournamentsquad'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentregistration',
            unique_together={('tournament', 'team'), ('tournament', 'user')},
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='squad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='vent_tournament.tournamentsquad'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentregistration',
            unique_together={('tournament', 'squad'), ('tournament', 'team'), ('tournament', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='tournamentsquad',
            unique_together={('tournament', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='squadmember',
            unique_together={('squad', 'user')},
        ),
    ]
