# Generated by Django 5.0.7 on 2026-09-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0039_squadmember_tournamentsquad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastelement',
            name='kind',
            field=models.CharField(choices=[('scorebar', 'Score bar'), ('standings', 'Standings table'), ('lower_third', 'Lower third'), ('player_card', 'Player card'), ('bracket', 'Bracket'), ('sponsors', 'Sponsor wall'), ('media', 'Clip or picture'), ('squad_depth', 'Squad depth'), ('ticker', 'Ticker'), ('intro', 'Intro'), ('outro', 'Outro'), ('now_next', 'Now and next'), ('programme', 'Programme'), ('doors', 'Doors')], max_length=20),
        ),
    ]
