# Generated by Django 5.0.7 on 2026-09-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0040_alter_broadcastelement_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studioasset',
            name='kind',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('font', 'Font')], max_length=8),
        ),
    ]
