# Generated by Django 5.0.7 on 2026-09-04 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0032_shortlink_tournament_alter_shortlink_event_and_more'),
        ('vent_tournament', '0041_alter_studioasset_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RunSheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=140)),
                ('subtitle', models.CharField(blank=True, default='', max_length=240)),
                ('token', models.CharField(db_index=True, max_length=48, unique=True)),
                ('visibility', models.CharField(choices=[('private', 'Only me and my team'), ('link', 'Anybody with the link'), ('public', 'On the event page, and findable')], default='private', max_length=8)),
                ('time_zone', models.CharField(default='Africa/Lagos', max_length=64)),
                ('show_owners', models.BooleanField(default=True)),
                ('show_notes', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_sheets', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='run_sheets', to='vent_event.event')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='run_sheets', to='vent_tournament.tournament')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RunSheetDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=80)),
                ('date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=240)),
                ('position', models.PositiveIntegerField(default=0)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='vent_tournament.runsheet')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RunSheetItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phase', models.CharField(blank=True, default='', max_length=80)),
                ('activity', models.CharField(max_length=400)),
                ('owner', models.CharField(blank=True, default='', max_length=120)),
                ('match', models.CharField(blank=True, default='', max_length=120)),
                ('starts_at', models.TimeField(blank=True, null=True)),
                ('ends_at', models.TimeField(blank=True, null=True)),
                ('minutes', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('is_confirmed', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vent_tournament.runsheetday')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
