# Generated by Django 5.0.7 on 2026-09-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0042_runsheet_runsheetday_runsheetitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastelement',
            name='kind',
            field=models.CharField(choices=[('scorebar', 'Score bar'), ('standings', 'Standings table'), ('lower_third', 'Lower third'), ('player_card', 'Player card'), ('bracket', 'Bracket'), ('sponsors', 'Sponsor wall'), ('media', 'Clip or picture'), ('squad_depth', 'Squad depth'), ('ticker', 'Ticker'), ('intro', 'Intro'), ('outro', 'Outro'), ('fixture_card', 'Fixture card'), ('fixture_result', 'Fixture result'), ('match_result', 'Match result'), ('head_to_head', 'Head to head'), ('break_screen', 'Break screen'), ('now_next', 'Now and next'), ('award', 'Award'), ('explainer', 'Explainer'), ('programme', 'Programme'), ('doors', 'Doors')], max_length=20),
        ),
    ]
