# Generated by Django 5.0.7 on 2026-09-04 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0044_broadcastsession_theme_alter_broadcastelement_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverlayTextLayer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, default='', max_length=240)),
                ('field', models.CharField(blank=True, default='', max_length=120)),
                ('font_size', models.SmallIntegerField(default=64)),
                ('colour', models.CharField(default='#FFFFFF', max_length=9)),
                ('family', models.CharField(choices=[('house', 'V-ENT house'), ('condensed', 'Condensed'), ('display', 'Display'), ('accent', 'Accent')], default='house', max_length=12)),
                ('font_slot', models.CharField(blank=True, default='', max_length=40)),
                ('weight', models.SmallIntegerField(choices=[(400, 'Regular'), (600, 'Medium'), (800, 'Bold')], default=600)),
                ('align', models.CharField(choices=[('left', 'Left'), ('centre', 'Centre'), ('right', 'Right')], default='centre', max_length=8)),
                ('position', models.CharField(default='bottom_centre', max_length=16)),
                ('offset_x', models.IntegerField(default=0)),
                ('offset_y', models.IntegerField(default=0)),
                ('entry', models.CharField(default='rise', max_length=12)),
                ('exit', models.CharField(default='fade', max_length=12)),
                ('delay_ms', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('order', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_layers', to='vent_tournament.broadcastelement')),
                ('overlay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_layers', to='vent_tournament.tournamentoverlay')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
