# Generated by Django 5.0.7 on 2026-09-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0045_overlaytextlayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentoverlay',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
