# Generated by Django 5.0.7 on 2026-09-06 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0047_overlay_layer_kinds'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastSlot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('bg', 'Background'), ('full', 'Full frame'), ('lower', 'Lower third'), ('bug', 'Corner bug')], max_length=10)),
                ('item_kind', models.CharField(blank=True, default='', max_length=32)),
                ('active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overlay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='vent_tournament.tournamentoverlay')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='vent_tournament.broadcastsession')),
            ],
            options={
                'ordering': ['session_id', 'role'],
            },
        ),
        migrations.AddConstraint(
            model_name='broadcastslot',
            constraint=models.UniqueConstraint(fields=('session', 'role'), name='one_slot_per_role_per_session'),
        ),
    ]
