# Generated by Django 5.0.7 on 2026-09-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0049_alter_tournament_options_alter_tournament_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentstage',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentstage',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tournamentstage',
            name='place_type',
            field=models.CharField(blank=True, choices=[('', 'Same as the tournament'), ('online', 'Online'), ('physical', 'At a venue'), ('hybrid', 'Both')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='tournamentstage',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentstage',
            name='virtual_link',
            field=models.URLField(blank=True, default='', max_length=400),
        ),
    ]
