# Generated by Django 5.0.7 on 2026-09-09 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0050_tournamentstage_ends_at_tournamentstage_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField()),
                ('warn_hours', models.PositiveIntegerField(default=24)),
                ('state', models.CharField(choices=[('scheduled', 'Waiting for its time'), ('warned', 'The organiser has been told it is coming'), ('paid', 'Paid'), ('cancelled', 'Called off before it ran'), ('failed', 'Tried and could not')], default='scheduled', max_length=20)),
                ('warned_at', models.DateTimeField(blank=True, null=True)),
                ('ran_at', models.DateTimeField(blank=True, null=True)),
                ('problem', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prize_schedules', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prize_schedule', to='vent_tournament.tournament')),
            ],
        ),
    ]
