"""Who bears the platform fee on an entry: the organiser (default, which is
what every tournament has been doing implicitly) or the player, on top.
"""
# Generated by Django 5.0.7 on 2026-09-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0051_prizeschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='fee_bearer',
            field=models.CharField(default='organiser', max_length=16),
        ),
    ]
