# Generated by Django 5.0.7 on 2026-09-27 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0053_runsheet_name_not_a_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracketmatch',
            name='best_of',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='check_in_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='checked_in_p1_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='checked_in_p2_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='draw_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='forfeit_reason',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='games',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='group_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='legs',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='penalties_p1',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='penalties_p2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='room_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='room_password',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='vent_tournament.tournamentstage'),
        ),
        migrations.AddField(
            model_name='matchscore',
            name='games',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='matchscore',
            name='penalties_p1',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchscore',
            name='penalties_p2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentstage',
            name='direct_entrants',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tournamentstage',
            name='drawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentstage',
            name='entrants',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tournamentstage',
            name='placement',
            field=models.CharField(choices=[('cross', 'Group winners against runners-up of another group'), ('by_record', 'By record across the whole stage'), ('random', 'Drawn at random'), ('manual', 'In the order the organiser sets')], default='cross', max_length=12),
        ),
        migrations.AddField(
            model_name='tournamentstage',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
