# Generated by Django 5.0.7 on 2026-09-28 10:36

import django.db.models.deletion
import vent_tournament.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0055_dispute_window_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bracketmatch',
            name='loser_place',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='winner_place',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bracketmatch',
            name='bracket_side',
            field=models.CharField(choices=[('winners', 'Winners bracket'), ('losers', 'Losers bracket'), ('grand_final', 'Grand final'), ('placement', 'Placement match')], default='winners', max_length=12),
        ),
        migrations.CreateModel(
            name='BRLobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='br_lobbies', to='vent_tournament.tournamentstage')),
            ],
            options={
                'ordering': ['stage_id', 'number'],
                'unique_together': {('stage', 'number')},
            },
        ),
        migrations.CreateModel(
            name='BRMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('map_name', models.CharField(blank=True, default='', max_length=60)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('room_code', models.CharField(blank=True, default='', max_length=64)),
                ('room_password', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Not played yet'), ('entered', 'Results entered')], default='pending', max_length=10)),
                ('entered_via', models.CharField(blank=True, choices=[('', 'Not entered'), ('manual', 'Typed in'), ('ocr', 'Read from a screenshot')], default='', max_length=8)),
                ('entered_at', models.DateTimeField(blank=True, null=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='br_maps_entered', to=settings.AUTH_USER_MODEL)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='vent_tournament.brlobby')),
            ],
            options={
                'ordering': ['lobby_id', 'number'],
                'unique_together': {('lobby', 'number')},
            },
        ),
        migrations.CreateModel(
            name='BROcrJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Waiting to be read'), ('reading', 'Being read'), ('ready', 'Ready to review'), ('failed', 'Could not be read'), ('committed', 'Saved as the results')], default='queued', max_length=10)),
                ('engine', models.CharField(blank=True, default='', max_length=40)),
                ('rows', models.JSONField(blank=True, default=list)),
                ('error_code', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='br_ocr_jobs', to=settings.AUTH_USER_MODEL)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_jobs', to='vent_tournament.brmap')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BROcrImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=200, storage=vent_tournament.models._br_private_storage, upload_to=vent_tournament.models._br_screenshot_path)),
                ('content_type', models.CharField(max_length=20)),
                ('size', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vent_tournament.brocrjob')),
            ],
            options={
                'ordering': ['job_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.BooleanField(default=True)),
                ('placement', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('kills', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('damage', models.PositiveIntegerField(default=0)),
                ('bonus', models.FloatField(default=0)),
                ('penalty', models.FloatField(default=0)),
                ('adjustment_note', models.CharField(blank=True, default='', max_length=200)),
                ('placement_points', models.FloatField(default=0)),
                ('kill_points', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='vent_tournament.brmap')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='br_results', to='vent_tournament.tournamentregistration')),
            ],
            options={
                'ordering': ['map_id', 'placement', 'id'],
                'unique_together': {('map', 'registration')},
            },
        ),
        migrations.CreateModel(
            name='BRPlayerLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=60)),
                ('kills', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('damage', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='br_lines', to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='vent_tournament.brresult')),
            ],
            options={
                'ordering': ['result_id', '-kills', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BRLobbySeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.PositiveSmallIntegerField(default=0)),
                ('carried_points', models.FloatField(default=0)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='vent_tournament.brlobby')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='br_seats', to='vent_tournament.tournamentregistration')),
            ],
            options={
                'ordering': ['lobby_id', 'seat', 'id'],
                'unique_together': {('lobby', 'registration')},
            },
        ),
        migrations.CreateModel(
            name='BRNameAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='br_aliases', to='vent_tournament.tournamentregistration')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='br_aliases', to='vent_tournament.tournament')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='br_aliases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tournament', 'screen_name')},
            },
        ),
    ]
