# Generated by Django 5.2.17 on 2026-09-30 01:35

import vent_auth.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0056_battle_royale_and_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsors',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=vent_auth.uploads.OpaqueName('sponsor_logos/')),
        ),
        migrations.AlterField(
            model_name='studioasset',
            name='file',
            field=models.FileField(upload_to=vent_auth.uploads.OpaqueName('studio_assets/')),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rules_document',
            field=models.FileField(blank=True, null=True, upload_to=vent_auth.uploads.OpaqueName('tournament_rules/')),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_banner',
            field=models.ImageField(blank=True, null=True, upload_to=vent_auth.uploads.OpaqueName('tournament_banners/')),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_logo',
            field=models.ImageField(blank=True, null=True, upload_to=vent_auth.uploads.OpaqueName('tournament_logos/')),
        ),
        migrations.AlterField(
            model_name='tournamentoverlay',
            name='file',
            field=models.FileField(upload_to=vent_auth.uploads.OpaqueName('tournament_overlays/')),
        ),
        migrations.AlterField(
            model_name='tournamentsquad',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=vent_auth.uploads.OpaqueName('squad_logos/')),
        ),
    ]
