# Generated by Django 5.2.17 on 2026-09-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0058_designed_overlays'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastsession',
            name='style',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
