# Generated by Django 5.2.17 on 2026-09-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_tournament', '0059_overlay_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastelement',
            name='kind',
            field=models.CharField(choices=[('scorebar', 'Score bar'), ('standings', 'Standings table'), ('lower_third', 'Lower third'), ('player_card', 'Player card'), ('bracket', 'Bracket'), ('sponsors', 'Sponsor wall'), ('media', 'Clip or picture'), ('squad_depth', 'Squad depth'), ('ticker', 'Ticker'), ('intro', 'Intro'), ('outro', 'Outro'), ('fixture_card', 'Fixture card'), ('fixture_result', 'Fixture result'), ('match_result', 'Match result'), ('head_to_head', 'Head to head'), ('break_screen', 'Break screen'), ('now_next', 'Now and next'), ('award', 'Award'), ('explainer', 'Explainer'), ('desk_lower_third', 'Desk lower third'), ('matchday', 'Matchday card'), ('analyst_desk', 'Analyst desk frame'), ('play_area', 'Play area frame'), ('starting_soon', 'Starting soon'), ('transition', 'Transition'), ('brb', 'Be right back'), ('stream_ended', 'Stream ended'), ('champions', 'Champions'), ('streamer_single', 'Streamer frame'), ('streamer_double', 'Two streamers frame'), ('streamer_gameplay', 'Streamer and game frame'), ('name_tag', 'Name tag'), ('match_lower_third', 'Match lower third'), ('programme', 'Programme'), ('doors', 'Doors')], max_length=20),
        ),
    ]
