# Generated by Django 5.0.7 on 2026-08-26 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vent_auth', '0041_team_description_no_placeholder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('partner_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('contact_name', models.CharField(max_length=140)),
                ('contact_email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('intended_use', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('requested_scopes', models.JSONField(blank=True, default=list)),
                ('approved_scopes', models.JSONField(blank=True, default=list)),
                ('sso_status', models.CharField(choices=[('none', 'Not requested'), ('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20)),
                ('legal_name', models.CharField(blank=True, default='', max_length=200)),
                ('registration_number', models.CharField(blank=True, default='', max_length=80)),
                ('privacy_policy_url', models.URLField(blank=True, default='')),
                ('terms_url', models.URLField(blank=True, default='')),
                ('data_protection_contact', models.EmailField(blank=True, default='', max_length=254)),
                ('redirect_uris', models.JSONField(blank=True, default=list)),
                ('sso_client_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('sso_client_secret_hash', models.CharField(blank=True, default='', max_length=128)),
                ('review_note', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='vent_auth.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OAuthAuthorizationCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_hash', models.CharField(db_index=True, max_length=128)),
                ('redirect_uri', models.URLField()),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('code_challenge', models.CharField(blank=True, default='', max_length=128)),
                ('code_challenge_method', models.CharField(blank=True, default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_auth_codes', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_codes', to='vent_partners.partner')),
            ],
        ),
        migrations.CreateModel(
            name='OAuthAccessToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=128)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_tokens', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='vent_partners.partner')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerApiKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default key', max_length=120)),
                ('key_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('secret_hash', models.CharField(max_length=128)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_partner_keys', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='vent_partners.partner')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ExternalIdentity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=40)),
                ('external_id', models.CharField(max_length=190)),
                ('external_username', models.CharField(blank=True, default='', max_length=190)),
                ('external_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('provider', 'external_id')},
            },
        ),
    ]
