# Generated by Django 5.0.7 on 2026-08-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='verification_secret',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='partner',
            name='verification_url',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
    ]
