# Generated by Django 5.0.7 on 2026-08-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_partners', '0002_partner_verification_endpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundLogin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=40)),
                ('state', models.CharField(db_index=True, max_length=190, unique=True)),
                ('code_verifier', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
