# Generated by Django 5.0.7 on 2026-09-10 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeAd',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=140)),
                ('image', models.ImageField(blank=True, null=True, upload_to='anime/ads/')),
                ('url', models.URLField(blank=True, default='')),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-weight', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chapter_id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('number', models.DecimalField(decimal_places=2, max_digits=7)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('early_access_vc', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('battle_id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=180, null=True, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('state', models.CharField(choices=[('nominating', 'Taking nominations'), ('voting', 'Voting is open'), ('closed', 'Decided')], default='nominating', max_length=12)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anime_battles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleCharacter',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('source', models.CharField(blank=True, default='', max_length=140)),
                ('image', models.ImageField(blank=True, null=True, upload_to='anime/characters/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='vent_anime.battle')),
                ('nominated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anime_nominations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('battle', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BattleComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_battle_comments', to=settings.AUTH_USER_MODEL)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vent_anime.battle')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChapterComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_comments', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vent_anime.chapter')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='vent_anime.chaptercomment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReaderSettings',
            fields=[
                ('settings_id', models.AutoField(primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('single', 'One page'), ('double', 'Two pages'), ('vertical', 'Keep scrolling')], default='single', max_length=10)),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('sepia', 'Sepia'), ('black', 'True black')], default='dark', max_length=10)),
                ('font_scale', models.PositiveSmallIntegerField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anime_reader_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingRoom',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, db_index=True, max_length=24, null=True, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('privacy', models.CharField(choices=[('public', 'Anybody can join'), ('private', 'Only people I invite'), ('password', 'Anybody with the password')], default='private', max_length=10)),
                ('password_hash', models.CharField(blank=True, default='', max_length=128)),
                ('control', models.CharField(choices=[('host', 'The host turns the page'), ('anyone', 'Anybody can turn the page')], default='host', max_length=8)),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='vent_anime.chapter')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anime_rooms_driving', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_rooms_hosted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomAnnotation',
            fields=[
                ('annotation_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('kind', models.CharField(choices=[('highlight', 'Highlighted area'), ('note', 'Sticky note'), ('drawing', 'Drawing')], default='note', max_length=10)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('w', models.FloatField(default=0)),
                ('h', models.FloatField(default=0)),
                ('text', models.CharField(blank=True, default='', max_length=500)),
                ('path', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_annotations', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='vent_anime.chapter')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='vent_anime.readingroom')),
            ],
            options={
                'ordering': ['annotation_id'],
            },
        ),
        migrations.CreateModel(
            name='RoomInvite',
            fields=[
                ('invite_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='vent_anime.readingroom')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('series_id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=180, null=True, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('synopsis', models.TextField(blank=True, default='')),
                ('kind', models.CharField(choices=[('manga', 'Manga'), ('manhwa', 'Manhwa'), ('webcomic', 'Webcomic')], default='manga', max_length=12)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('hiatus', 'On hiatus')], default='ongoing', max_length=12)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='anime/covers/')),
                ('genres', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('visibility', models.CharField(choices=[('public', 'Anybody can find it'), ('private', 'Only me')], default='private', max_length=10)),
                ('pricing', models.CharField(choices=[('free', 'Free for everybody'), ('per_chapter', 'Paid, chapter by chapter'), ('subscription', 'A subscription to the series')], default='free', max_length=14)),
                ('chapter_price_vc', models.PositiveIntegerField(default=0)),
                ('subscription_price_vc', models.PositiveIntegerField(default=0)),
                ('boosted_until', models.DateTimeField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('rating_total', models.PositiveIntegerField(default=0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_series', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='readingroom',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='vent_anime.series'),
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='vent_anime.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_progress', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='vent_anime.series')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoMessage',
            fields=[
                ('promo_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('sent_to', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_promos', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promos', to='vent_anime.series')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='vent_anime.series'),
        ),
        migrations.CreateModel(
            name='SeriesFollow',
            fields=[
                ('follow_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='vent_anime.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_follows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeriesRating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('stars', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='vent_anime.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeriesSubscription',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='vent_anime.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-until'],
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('volume_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=160)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='vent_anime.series')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='vent_anime.volume'),
        ),
        migrations.CreateModel(
            name='AttributeVote',
            fields=[
                ('vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute', models.CharField(max_length=16)),
                ('score', models.PositiveSmallIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_votes', to=settings.AUTH_USER_MODEL)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='vent_anime.battlecharacter')),
            ],
            options={
                'indexes': [models.Index(fields=['character', 'attribute'], name='vent_anime__charact_bba14b_idx')],
                'unique_together': {('character', 'user', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('bookmark_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='vent_anime.chapter')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'chapter', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='ChapterPurchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('coins', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('early', 'Early access'), ('chapter', 'A paid chapter')], default='chapter', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='vent_anime.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_chapter_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'chapter')},
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='anime/pages/')),
                ('alt', models.CharField(blank=True, default='', max_length=300)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='vent_anime.chapter')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('chapter', 'number')},
            },
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('was_removed', models.BooleanField(default=False)),
                ('pages_seen', models.PositiveIntegerField(default=0)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='vent_anime.readingroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_room_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('room', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RoomMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('chat', 'Said something'), ('reaction', 'Reacted')], default='chat', max_length=8)),
                ('body', models.CharField(blank=True, default='', max_length=1000)),
                ('emoji', models.CharField(blank=True, default='', max_length=16)),
                ('page_number', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_room_messages', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='vent_anime.readingroom')),
            ],
            options={
                'ordering': ['message_id'],
                'indexes': [models.Index(fields=['room', 'message_id'], name='vent_anime__room_id_d48f02_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoomSignal',
            fields=[
                ('signal_id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=12)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_signals_sent', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='vent_anime.readingroom')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_signals_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['signal_id'],
                'indexes': [models.Index(fields=['room', 'to_user', 'signal_id'], name='vent_anime__room_id_306636_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['visibility', 'status'], name='vent_anime__visibil_4f3091_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['author', '-created_at'], name='vent_anime__author__c5fe92_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='readingprogress',
            unique_together={('user', 'series')},
        ),
        migrations.AlterUniqueTogether(
            name='seriesfollow',
            unique_together={('user', 'series')},
        ),
        migrations.AlterUniqueTogether(
            name='seriesrating',
            unique_together={('user', 'series')},
        ),
        migrations.AlterUniqueTogether(
            name='seriessubscription',
            unique_together={('user', 'series')},
        ),
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together={('series', 'number')},
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['series', 'number'], name='vent_anime__series__81b277_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('series', 'number')},
        ),
    ]
