"""The platform's whole coins out of a chapter sale, at the dashboard rate
(`anime_fee_pct`, 0 today) when the sale was made. Rows before this carry 0,
which is what the platform took.
"""
# Generated by Django 5.0.7 on 2026-09-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterpurchase',
            name='fee_vc',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
