# Generated by Django 5.2.17 on 2026-09-30 01:35

import vent_auth.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_anime', '0002_chapter_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animead',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=vent_auth.uploads.OpaqueName('anime/ads/')),
        ),
        migrations.AlterField(
            model_name='battlecharacter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=vent_auth.uploads.OpaqueName('anime/characters/')),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(upload_to=vent_auth.uploads.OpaqueName('anime/pages/')),
        ),
        migrations.AlterField(
            model_name='series',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=vent_auth.uploads.OpaqueName('anime/covers/')),
        ),
    ]
