# Generated by Django 5.0.7 on 2026-09-08 13:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vent_auth', '0078_kycdocument_provider_kycdocument_provider_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=160, null=True, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('tagline', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('price_vc', models.IntegerField(default=0)),
                ('price_ngn', models.IntegerField(default=0)),
                ('interval', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('trial_days', models.PositiveIntegerField(default=0)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('member_content', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('public', 'Public'), ('retired', 'Retired')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='vent_auth.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['price_vc', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=32, unique=True)),
                ('plan_name', models.CharField(blank=True, default='', max_length=120)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('amount_vc', models.IntegerField(default=0)),
                ('amount_ngn', models.IntegerField(default=0)),
                ('collected_vc', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('open', 'Open'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('void', 'Void')], db_index=True, default='open', max_length=10)),
                ('source', models.CharField(default='wallet', max_length=10)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=64)),
                ('failure_code', models.CharField(blank=True, default='', max_length=40)),
                ('failure_detail', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='vent_billing.plan')),
            ],
            options={
                'ordering': ['-created_at', '-invoice_id'],
            },
        ),
        migrations.CreateModel(
            name='BillingSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_vc', models.IntegerField(default=0)),
                ('lines_paid', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='vent_billing.plan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('organiser', 'Organiser'), ('platform', 'Platform fee'), ('reversal', 'Reversal')], max_length=12)),
                ('amount_vc', models.IntegerField(default=0)),
                ('gross_vc', models.IntegerField(default=0)),
                ('fee_vc', models.IntegerField(default=0)),
                ('fee_pct', models.FloatField(default=0)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vent_auth.organization')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vent_billing.billingledgerentry')),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vent_billing.billingledgerentry')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='vent_billing.billingsettlement')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='vent_billing.invoice')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='vent_billing.plan')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=32, unique=True)),
                ('state', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='active', max_length=12)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField(db_index=True)),
                ('anchor_day', models.PositiveSmallIntegerField(default=1)),
                ('anchor_month', models.PositiveSmallIntegerField(default=1)),
                ('source', models.CharField(choices=[('wallet', 'VENT COINS wallet'), ('card', 'Saved card'), ('none', 'Nothing to charge')], default='wallet', max_length=10)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('dunning_attempt', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='vent_auth.savedcard')),
                ('pending_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_subscriptions', to='vent_billing.plan')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='vent_billing.plan')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='vent_billing.subscription'),
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(blank=True, default='', max_length=12)),
                ('to_state', models.CharField(max_length=12)),
                ('reason', models.CharField(max_length=40)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='vent_billing.subscription')),
            ],
            options={
                'ordering': ['-at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['org', 'status'], name='vent_billin_org_id_a4d942_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['owner', 'status'], name='vent_billin_owner_i_707ba9_idx'),
        ),
        migrations.AddIndex(
            model_name='billingledgerentry',
            index=models.Index(fields=['plan', 'settled_at'], name='vent_billin_plan_id_c4c469_idx'),
        ),
        migrations.AddIndex(
            model_name='billingledgerentry',
            index=models.Index(fields=['user', 'settled_at'], name='vent_billin_user_id_c774e9_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['state', 'period_end'], name='vent_billin_state_f929aa_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['subscriber', 'state'], name='vent_billin_subscri_ff96e7_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['subscription', 'state'], name='vent_billin_subscri_a7fde8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('subscription', 'period_start', 'attempt')},
        ),
    ]
