# Generated by Django 5.0.7 on 2026-03-22 17:53
# Modified: state-only — Railway DB already has these columns from pythonanywhere.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0019_remove_teams_team_privacy_and_more'),
        ('vent_team', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='teaminterests',
                    name='team',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vent_team_interests', to='vent_auth.teams'),
                ),
                migrations.AlterField(
                    model_name='teammembers',
                    name='team',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vent_team_members', to='vent_auth.teams'),
                ),
            ]
        ),
    ]
