# Generated by Django 5.0.7 on 2026-07-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vent_team', '0002_alter_teaminterests_team_alter_teammembers_team'),
        # Must run AFTER the vent_auth data upsert reads vent_team.TeamMembers,
        # so the table is only dropped once its rows have been consolidated.
        ('vent_auth', '0026_teammembers_role_teams_join_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMembers',
        ),
    ]
