# Generated by Django 5.0.7 on 2024-10-21 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=8)),
                ('desc', models.CharField(max_length=140)),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reg_start_date', models.DateTimeField()),
                ('reg_end_date', models.DateTimeField()),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('event_link', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='event_logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='event_banners/')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('social_link_id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='vent_event.event')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('sponsor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='sponsor_logos/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='vent_event.event')),
            ],
        ),
    ]
