# Generated by Django 5.0.7 on 2026-08-17 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0005_event_link_location_nullable_db'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=18, unique=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('checked_in', 'Checked in'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='valid', max_length=20)),
                ('price_vc', models.PositiveIntegerField(default=0)),
                ('price_ngn', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_checked_in', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='vent_event.event')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='vent_event.tickettier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
    ]
