# Generated by Django 5.0.7 on 2026-08-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0006_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attendee_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='ticket',
            name='attendee_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='ticket',
            name='attendee_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
