# Generated by Django 5.0.7 on 2026-08-17 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0008_vendor_vendororder_vendorproduct_vendororderitem'),
        ('vent_tournament', '0012_reconcile_tournament_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTournamentLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shared_ticketing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_links', to='vent_event.event')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_tournament_links', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_link', to='vent_tournament.tournament')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
