# Generated by Django 5.0.7 on 2026-08-26 00:29

from django.db import migrations, models


from django.utils.text import slugify


def _fill(apps, schema_editor, app_label, model_name, name_field, pk_field):
    """Give every existing row a readable address.

    Done in the migration rather than lazily, so a link to an old tournament
    works the moment this deploys rather than the next time somebody edits it.
    """
    Model = apps.get_model(app_label, model_name)
    taken = set(
        Model.objects.exclude(slug__isnull=True).exclude(slug='').values_list('slug', flat=True)
    )
    for row in Model.objects.filter(slug__isnull=True) | Model.objects.filter(slug=''):
        base = slugify(getattr(row, name_field, '') or '')[:150] or str(getattr(row, pk_field))
        candidate, n = base, 2
        while candidate in taken:
            candidate = f'{base[:150]}-{n}'
            n += 1
        taken.add(candidate)
        row.slug = candidate
        row.save(update_fields=['slug'])


def _clear(apps, schema_editor, app_label, model_name):
    apps.get_model(app_label, model_name).objects.update(slug=None)


def fill(apps, schema_editor):
    _fill(apps, schema_editor, 'vent_event', 'Event', 'name', 'event_id')


def clear(apps, schema_editor):
    _clear(apps, schema_editor, 'vent_event', 'Event')


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0009_eventtournamentlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, null=True, unique=True),
        ),
            migrations.RunPython(fill, clear),
    ]
