# Generated by Django 5.0.7 on 2026-08-27 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0011_event_series'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['kind', 'sort_order', 'sponsor_id']},
        ),
        migrations.AddField(
            model_name='sponsor',
            name='kind',
            field=models.CharField(choices=[('sponsor', 'Sponsor'), ('partner', 'Partner')], default='sponsor', max_length=10),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='SponsorLink',
            fields=[
                ('sponsor_link_id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=500)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='vent_event.sponsor')),
            ],
        ),
    ]
