# Generated by Django 5.0.7 on 2026-08-27 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0051_fold_annual_titles_into_series'),
        ('vent_event', '0012_alter_sponsor_options_sponsor_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickettier',
            options={'ordering': ['day', 'id']},
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='vent_auth.organization'),
        ),
        migrations.AddField(
            model_name='tickettier',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickettier',
            name='day_label',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.CreateModel(
            name='EventReferral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=40)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('allocation', models.PositiveIntegerField(default=0)),
                ('sold', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='vent_event.event')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='vent_event.sponsor')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('event', 'code')},
            },
        ),
        migrations.CreateModel(
            name='EventManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('door', 'Door staff')], default='manager', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_managers_added', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='vent_event.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='EventPromo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40)),
                ('kind', models.CharField(choices=[('percent', 'Percent off'), ('amount', 'Amount off')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_tickets', models.PositiveIntegerField(default=0)),
                ('used_tickets', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promos', to='vent_event.event')),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promos', to='vent_event.tickettier')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promos', to='vent_event.eventreferral')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('event', 'code')},
            },
        ),
    ]
