# Generated by Django 5.0.7 on 2026-08-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0013_alter_tickettier_options_event_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
    ]
