# Generated by Django 5.0.7 on 2026-08-28 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0014_event_currency'),
        ('vent_tournament', '0021_tournament_stages'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=140)),
                ('description', models.CharField(blank=True, default='', max_length=400)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('stage', models.CharField(blank=True, default='', max_length=100)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='vent_event.event')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_sessions', to='vent_tournament.tournament')),
            ],
            options={
                'ordering': ['starts_at', 'session_id'],
            },
        ),
    ]
