# Generated by Django 5.0.7 on 2026-08-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0015_event_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='checked_in_gate',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
