# Generated by Django 5.0.7 on 2026-08-28 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0016_ticket_gate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketHold',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('guest', 'Guest list'), ('press', 'Press'), ('venue', 'Venue allocation'), ('artist', 'Artist and crew'), ('other', 'Other')], default='guest', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('issued', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_holds', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='vent_event.event')),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='vent_event.tickettier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
