# Generated by Django 5.0.7 on 2026-08-28 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0018_waitlist_and_pricing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EventCheckoutField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('phone', 'Phone number'), ('number', 'A number'), ('choice', 'One of a list'), ('checkbox', 'A yes or no')], default='text', max_length=20)),
                ('help_text', models.CharField(blank=True, default='', max_length=200)),
                ('required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list)),
                ('per_ticket', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_fields', to='vent_event.event')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
