# Generated by Django 5.0.7 on 2026-08-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0019_guest_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
