# Generated by Django 5.0.7 on 2026-08-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0020_ticket_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_tickets_per_email',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
