# Generated by Django 5.0.7 on 2026-08-29 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0021_event_max_tickets_per_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettier',
            name='unlocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks_tiers', to='vent_event.eventreferral'),
        ),
    ]
