# Generated by Django 5.0.7 on 2026-08-29 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0022_tickettier_unlocked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtournamentlink',
            name='entry_mode',
            field=models.CharField(choices=[('ticket', 'An event ticket is the entry'), ('own_fee', 'The tournament charges its own entry fee'), ('free', 'Free either way')], default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='eventtournamentlink',
            name='entry_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admits_to_tournaments', to='vent_event.tickettier'),
        ),
        migrations.AddField(
            model_name='eventtournamentlink',
            name='reward_from_round',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventtournamentlink',
            name='reward_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_by_tournaments', to='vent_event.tickettier'),
        ),
    ]
