# Generated by Django 5.0.7 on 2026-08-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0023_eventtournamentlink_entry_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='directions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='map_link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='self_check_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='self_check_in_opens_minutes',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_name',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
    ]
