# Generated by Django 5.0.7 on 2026-08-29 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0026_event_latitude_event_longitude_eventattendeeorigin'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpoll',
            name='help_text',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
        migrations.AddField(
            model_name='eventpoll',
            name='kind',
            field=models.CharField(choices=[('single', 'Pick one'), ('multiple', 'Pick several'), ('scale', 'Rate on a scale'), ('short_text', 'Short answer'), ('long_text', 'Long answer'), ('ranking', 'Put in order')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='eventpoll',
            name='max_choices',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventpoll',
            name='min_choices',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventpoll',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventpoll',
            name='scale_max',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='eventpoll',
            name='scale_max_label',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='eventpoll',
            name='scale_min',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='eventpoll',
            name='scale_min_label',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='eventpollvote',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpollvote',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='eventpollvote',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='vent_event.eventpolloption'),
        ),
        migrations.CreateModel(
            name='EventPollChoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='vent_event.eventpolloption')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='vent_event.eventpollvote')),
            ],
            options={
                'ordering': ['position', 'id'],
                'unique_together': {('vote', 'option')},
            },
        ),
    ]
