# Generated by Django 5.0.7 on 2026-08-29 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0027_eventpoll_help_text_eventpoll_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpoll',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reveals', to='vent_event.eventpoll'),
        ),
        migrations.AddField(
            model_name='eventpoll',
            name='depends_on_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpoll',
            name='depends_on_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpoll',
            name='depends_on_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reveals', to='vent_event.eventpolloption'),
        ),
    ]
