# Generated by Django 5.0.7 on 2026-08-29 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0028_eventpoll_depends_on_eventpoll_depends_on_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='vent_event.eventreferral'),
        ),
        migrations.CreateModel(
            name='ReferralDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField(db_index=True)),
                ('visits', models.PositiveIntegerField(default=0)),
                ('visitors', models.PositiveIntegerField(default=0)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='vent_event.eventreferral')),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('referral', 'day')},
            },
        ),
    ]
