# Generated by Django 5.0.7 on 2026-09-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0030_tickettier_max_tickets_per_email_shortlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity_mode',
            field=models.CharField(choices=[('per_day', 'Each day starts afresh'), ('total', 'Counted across the whole event')], default='per_day', max_length=10),
        ),
    ]
