# Generated by Django 5.0.7 on 2026-09-02 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0031_event_capacity_mode'),
        ('vent_tournament', '0031_broadcastsession_broadcastelement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_links', to='vent_tournament.tournament'),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_links', to='vent_event.event'),
        ),
        migrations.AddConstraint(
            model_name='shortlink',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('event__isnull', False), ('tournament__isnull', True)), models.Q(('event__isnull', True), ('tournament__isnull', False)), _connector='OR'), name='shortlink_has_exactly_one_owner'),
        ),
    ]
