# Generated by Django 5.0.7 on 2026-09-06 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0032_shortlink_tournament_alter_shortlink_event_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.CreateModel(
            name='DoorLookup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=120)),
                ('matched', models.PositiveIntegerField(default=0)),
                ('gate', models.CharField(blank=True, default='', max_length=60)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('asked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='door_lookups', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_lookups', to='vent_event.event')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lookups', to='vent_event.ticket')),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['event', '-at'], name='vent_event__event_i_8b7914_idx')],
            },
        ),
    ]
