# Generated by Django 5.0.7 on 2026-09-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0033_ticket_updated_at_doorlookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorlookup',
            name='kind',
            field=models.CharField(choices=[('search', 'Search'), ('lookup', 'Code lookup'), ('undo', 'Check-in undone')], db_index=True, default='search', max_length=10),
        ),
    ]
