# Generated by Django 5.0.7 on 2026-09-07 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0035_vendor_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorSlot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=60)),
                ('price_ngn', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sold', models.PositiveIntegerField(default=0)),
                ('rules', models.TextField(blank=True, default='')),
                ('rules_version', models.PositiveIntegerField(default=1)),
                ('requires_approval', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_slots', to='vent_event.event')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorSlotPurchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price_vc', models.PositiveIntegerField(default=0)),
                ('price_ngn', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rules_accepted', models.TextField(blank=True, default='')),
                ('rules_version_accepted', models.PositiveIntegerField(default=1)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_slot_purchases', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='vent_event.vendorslot')),
                ('vendor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_purchase', to='vent_event.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
