# Generated by Django 5.0.7 on 2026-09-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0036_vendorslot_vendorslotpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='delivery_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='delivery_fee_vc',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='delivery_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='delivery_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='delivery_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='fulfilment',
            field=models.CharField(choices=[('collect', 'Collect from the stall'), ('deliver', 'Delivered')], default='collect', max_length=10),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='tracking',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='vendororderitem',
            name='variant',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='can_deliver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='variants',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='vendororder',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('ready', 'Ready for collection'), ('collected', 'Collected'), ('sent', 'Sent for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='paid', max_length=20),
        ),
    ]
