# Generated by Django 5.0.7 on 2026-09-07 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0037_vendororder_delivered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFunnelDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField(db_index=True)),
                ('step', models.CharField(max_length=32)),
                ('ref', models.CharField(blank=True, default='', max_length=80)),
                ('count', models.PositiveIntegerField(default=0)),
                ('people', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_days', to='vent_event.event')),
            ],
            options={
                'ordering': ['day', 'step'],
                'indexes': [models.Index(fields=['event', 'day'], name='vent_event__event_i_4eb202_idx')],
                'unique_together': {('event', 'day', 'step', 'ref')},
            },
        ),
    ]
