# Generated by Django 5.0.7 on 2026-09-07 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0038_eventfunnelday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fee_bearer',
            field=models.CharField(choices=[('organiser', 'The organiser absorbs it'), ('buyer', 'The buyer pays it on top')], default='organiser', max_length=16),
        ),
        migrations.AddField(
            model_name='eventreferral',
            name='commission_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='eventreferral',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EventSettlement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_vc', models.IntegerField(default=0)),
                ('lines_paid', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='vent_event.event')),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_run', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventLedgerEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('organiser', 'Organiser'), ('platform', 'Platform fee'), ('affiliate', 'Affiliate commission'), ('reversal', 'Reversal')], db_index=True, max_length=16)),
                ('amount_vc', models.IntegerField(default=0)),
                ('gross_vc', models.IntegerField(default=0)),
                ('fee_vc', models.IntegerField(default=0)),
                ('fee_pct', models.FloatField(default=0)),
                ('fee_bearer', models.CharField(default='organiser', max_length=16)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('settled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='vent_event.event')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger', to='vent_event.eventreferral')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverses_line', to='vent_event.eventledgerentry')),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_of', to='vent_event.eventledgerentry')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger', to='vent_event.ticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_ledger', to=settings.AUTH_USER_MODEL)),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='vent_event.eventsettlement')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'kind', 'settled_at'], name='vent_event__event_i_58efbc_idx')],
            },
        ),
    ]
