# Generated by Django 5.0.7 on 2026-09-07 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0039_event_fee_bearer_eventreferral_commission_pct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTransfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('to_email', models.EmailField(blank=True, default='', max_length=254)),
                ('from_name', models.CharField(blank=True, default='', max_length=120)),
                ('to_name', models.CharField(blank=True, default='', max_length=120)),
                ('old_code', models.CharField(db_index=True, max_length=18)),
                ('new_code', models.CharField(db_index=True, max_length=18)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_given', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='vent_event.ticket')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
