# Generated by Django 5.0.7 on 2026-09-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0040_tickettransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreferral',
            name='payee_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
