# Generated by Django 5.0.7 on 2026-09-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0041_eventreferral_payee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodedAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=300, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('looked_up_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['address'],
            },
        ),
    ]
