# Generated by Django 5.0.7 on 2026-09-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0042_geocodedaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocodedaddress',
            name='matched',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
