# Generated by Django 5.0.7 on 2026-09-07 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0043_geocodedaddress_matched'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbandonedCheckout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('total_ngn', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abandoned_checkouts', to='vent_event.event')),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abandoned_checkouts', to='vent_event.tickettier')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['event', 'converted_at'], name='vent_event__event_i_b17549_idx')],
            },
        ),
    ]
