# Generated by Django 5.0.7 on 2026-09-12 18:46

from django.db import migrations, models


def coins_to_naira(apps, schema_editor):
    """Lines written while the ledger held whole coins: their naira is their
    coins times the coin, which is exact because they were floored to coins
    at the sale. Nothing under a coin was ever recorded, so nothing under a
    coin can be recovered here; from this migration on it is."""
    import os
    unit = int(os.environ.get('NGN_PER_COIN', '1000') or 1000)
    Entry = apps.get_model('vent_event', 'EventLedgerEntry')
    for line in Entry.objects.all().iterator():
        line.amount_ngn = line.amount_vc * unit
        line.gross_ngn = line.gross_vc * unit
        line.fee_ngn = line.fee_vc * unit
        line.save(update_fields=['amount_ngn', 'gross_ngn', 'fee_ngn'])


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0045_alter_event_options_alter_event_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventledgerentry',
            name='amount_ngn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='eventledgerentry',
            name='fee_flat_ngn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='eventledgerentry',
            name='fee_ngn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='eventledgerentry',
            name='gross_ngn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(coins_to_naira, migrations.RunPython.noop),
    ]
