# Generated by Django 5.0.7 on 2026-09-13 08:16

from django.db import migrations, models


def what_was_sold_before(apps, schema_editor):
    """Orders placed while a stall was paid in full: the items came to the
    coins times the coin, the stall earned all of it and was paid all of it,
    and there was no fee. Ledger lines with the fee on the buyer carried the
    whole fee there."""
    import os
    unit = int(os.environ.get('NGN_PER_COIN', '1000') or 1000)
    Order = apps.get_model('vent_event', 'VendorOrder')
    for order in Order.objects.all().iterator():
        order.items_ngn = order.total_vc * unit
        order.vendor_ngn = order.total_vc * unit
        order.vendor_paid_vc = order.total_vc
        order.save(update_fields=['items_ngn', 'vendor_ngn', 'vendor_paid_vc'])
    Entry = apps.get_model('vent_event', 'EventLedgerEntry')
    Entry.objects.filter(fee_bearer='buyer').update(buyer_fee_ngn=models.F('fee_ngn'))


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0046_ledger_in_naira'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventledgerentry',
            name='buyer_fee_ngn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vendor',
            name='carry_ngn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vendor',
            name='fee_bearer',
            field=models.CharField(choices=[('vendor', 'The stallholder absorbs it'), ('buyer', 'The buyer pays it on top')], default='vendor', max_length=16),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='buyer_fee_vc',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='fee_bearer',
            field=models.CharField(default='vendor', max_length=16),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='fee_flat_ngn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='fee_ngn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='fee_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='items_ngn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='vendor_ngn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='vendor_paid_vc',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(what_was_sold_before, migrations.RunPython.noop),
    ]
