"""One ledger for events and tournaments.

A tournament's entry fees, prizes and payout go through the same lines and the
same settlement run as an event's tickets (CEO, 13 September 2026: tournaments
pay organisers a share). A line names its event OR its tournament, and a
tournament line names the entry that paid it or the prize it paid out.
"""
# Generated by Django 5.0.7 on 2026-09-13 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0047_stall_fee_and_who_bears_it'),
        ('vent_tournament', '0052_tournament_money'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventledgerentry',
            name='prize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger', to='vent_tournament.prizepayout'),
        ),
        migrations.AddField(
            model_name='eventledgerentry',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger', to='vent_tournament.tournamentregistration'),
        ),
        migrations.AddField(
            model_name='eventledgerentry',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='vent_tournament.tournament'),
        ),
        migrations.AddField(
            model_name='eventsettlement',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='vent_tournament.tournament'),
        ),
        migrations.AlterField(
            model_name='eventledgerentry',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='vent_event.event'),
        ),
        migrations.AlterField(
            model_name='eventsettlement',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='vent_event.event'),
        ),
        migrations.AddIndex(
            model_name='eventledgerentry',
            index=models.Index(fields=['tournament', 'kind', 'settled_at'], name='vent_event__tournam_da2896_idx'),
        ),
    ]
