# Generated by Django 5.0.7 on 2026-09-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0048_tournament_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
