# Generated by Django 5.0.7 on 2026-09-18 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0049_event_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='vent_event.eventpromo'),
        ),
    ]
