# Generated by Django 5.0.7 on 2026-09-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0050_ticket_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorslotpurchase',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
