# Generated by Django 5.0.7 on 2026-09-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0053_ticket_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='abandonedcheckout',
            name='order',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
