# Generated by Django 5.0.7 on 2026-09-29 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0083_pin_and_code_lockout'),
        ('vent_event', '0054_checkout_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='min_age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DepartureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, default='', max_length=80)),
                ('visibility', models.CharField(default='off', max_length=8)),
                ('set_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_records', to='vent_event.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-set_at'],
            },
        ),
        migrations.CreateModel(
            name='EventPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_visibility', models.CharField(choices=[('off', 'Nobody'), ('mutuals', 'Mutuals'), ('event', 'Everyone at the event')], default='off', max_length=8)),
                ('departure_area', models.CharField(blank=True, default='', max_length=80)),
                ('departure_visibility', models.CharField(choices=[('off', 'Nobody'), ('mutuals', 'Mutuals'), ('approved', 'Mutuals and people I approve')], default='off', max_length=8)),
                ('departure_set_at', models.DateTimeField(blank=True, null=True)),
                ('pings_open', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='vent_event.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_presences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='EventPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, default='', max_length=140)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='sent', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vent_auth.conversation')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pings', to='vent_event.event')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pings_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pings_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('event', 'sender', 'recipient')},
            },
        ),
        migrations.CreateModel(
            name='DepartureApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_approvals', to=settings.AUTH_USER_MODEL)),
                ('presence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='vent_event.eventpresence')),
            ],
            options={
                'unique_together': {('presence', 'approved')},
            },
        ),
    ]
