# Generated by Django 5.2.17 on 2026-09-30 01:35

import vent_auth.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0055_going_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=vent_auth.uploads.OpaqueName('event_banners/')),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=vent_auth.uploads.OpaqueName('event_logos/')),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=vent_auth.uploads.OpaqueName('sponsor_logos/')),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=vent_auth.uploads.OpaqueName('vendor_banners/')),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=vent_auth.uploads.OpaqueName('vendor_logos/')),
        ),
        migrations.AlterField(
            model_name='vendorproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=vent_auth.uploads.OpaqueName('vendor_products/')),
        ),
    ]
