# Generated by Django 5.2.17 on 2026-09-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0056_alter_event_banner_alter_event_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='site_accent',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='event',
            name='site_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='site_headline',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='site_layout',
            field=models.CharField(default='poster', max_length=8),
        ),
        migrations.AddField(
            model_name='event',
            name='site_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='site_theme',
            field=models.CharField(default='dark', max_length=8),
        ),
    ]
