# Generated by Django 5.0.7 on 2026-10-08 23:10

import django.db.models.deletion
import vent_auth.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_event', '0057_event_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue_layout',
            field=models.ImageField(blank=True, null=True, upload_to=vent_auth.uploads.OpaqueName('venue_layouts/')),
        ),
        migrations.CreateModel(
            name='VendorSlotPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=vent_auth.uploads.OpaqueName('slot_pictures/'))),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='vent_event.vendorslot')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
