# Generated by Django 4.2.6 on 2024-06-06 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("vent_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Games",
            fields=[
                ("game_id", models.AutoField(primary_key=True, serialize=False)),
                ("game_name", models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="users",
            name="full_name",
        ),
        migrations.AddField(
            model_name="users",
            name="user_email",
            field=models.EmailField(default="yoyo", max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="users",
            name="user_password",
            field=models.CharField(default="ggg", max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="users",
            name="first_name",
            field=models.CharField(max_length=148),
        ),
        migrations.AlterField(
            model_name="users",
            name="last_name",
            field=models.CharField(max_length=148),
        ),
        migrations.CreateModel(
            name="Teams",
            fields=[
                ("team_id", models.IntegerField(primary_key=True, serialize=False)),
                ("team_name", models.CharField(max_length=60, unique=True)),
                ("creation_date", models.DateField(default=django.utils.timezone.now)),
                ("team_privacy", models.CharField(default="public", max_length=7)),
                ("matches", models.IntegerField(default=0)),
                (
                    "game_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vent_auth.games",
                    ),
                ),
                (
                    "team_owner_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamMembers",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("is_captain", models.BooleanField(default=False)),
                ("join_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "team_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vent_auth.teams",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
