# Generated by Django 4.2.13 on 2024-06-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vent_auth", "0003_genres_verificationtoken_remove_teammembers_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="user_email",
        ),
        migrations.RemoveField(
            model_name="users",
            name="user_password",
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(max_length=256),
        ),
    ]
