# Generated by Django 4.2.13 on 2024-06-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "vent_auth",
            "0004_remove_users_user_email_remove_users_user_password_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="username",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
