# Generated by Django 4.2.13 on 2024-06-24 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vent_auth", "0005_remove_userprofile_username_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("org_id", models.AutoField(primary_key=True, serialize=False)),
                ("org_name", models.CharField(max_length=148, unique=True)),
                (
                    "org_creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="teammembers",
            old_name="team_id",
            new_name="team",
        ),
        migrations.RenameField(
            model_name="teammembers",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="teams",
            old_name="game_id",
            new_name="game",
        ),
        migrations.RenameField(
            model_name="usercommunity",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="usergames",
            old_name="game_id",
            new_name="game",
        ),
        migrations.RenameField(
            model_name="usergames",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="usergenre",
            old_name="genre_id",
            new_name="genre",
        ),
        migrations.RenameField(
            model_name="usergenre",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="teams",
            name="matches",
        ),
        migrations.RemoveField(
            model_name="teams",
            name="team_owner_id",
        ),
        migrations.AddField(
            model_name="teams",
            name="team_creator",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_teams",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teams",
            name="team_owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_teams",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name="UserWallet",
            fields=[
                ("user_wallet_id", models.AutoField(primary_key=True, serialize=False)),
                ("wallet_balance", models.IntegerField(default=0)),
                ("user_wallet_pin", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamWallet",
            fields=[
                ("team_wallet_id", models.AutoField(primary_key=True, serialize=False)),
                ("wallet_balance", models.IntegerField(default=0)),
                ("team_wallet_pin", models.IntegerField(blank=True, null=True)),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="vent_auth.teams",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamProfile",
            fields=[
                (
                    "team_profile_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("matches", models.IntegerField(default=0)),
                ("tournament_played", models.IntegerField(default=0)),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vent_auth.teams",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrgWallet",
            fields=[
                ("org_wallet_id", models.AutoField(primary_key=True, serialize=False)),
                ("wallet_balance", models.IntegerField(default=0)),
                ("org_wallet_pin", models.IntegerField(blank=True, null=True)),
                (
                    "org",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="vent_auth.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameAccount",
            fields=[
                (
                    "game_account_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("game_username", models.CharField(max_length=20)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vent_auth.games",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
