# Generated by Django 5.0.7 on 2024-08-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0006_organization_rename_team_id_teammembers_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgwallet',
            name='org_wallet_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teamwallet',
            name='team_wallet_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='full_name',
            field=models.CharField(max_length=148, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='user_wallet_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
