# Generated by Django 5.0.7 on 2024-09-07 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0007_alter_orgwallet_org_wallet_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='country',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='VerificationTokenMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
