# Generated by Django 5.0.7 on 2024-09-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0008_users_country_verificationtokenmain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtoken',
            name='token',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='VerificationTokenMain',
        ),
    ]
