# Generated by Django 5.0.7 on 2024-10-21 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0009_alter_verificationtoken_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('interest_id', models.AutoField(primary_key=True, serialize=False)),
                ('interest_name', models.CharField(max_length=36, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserGames',
            new_name='FavoriteGames',
        ),
        migrations.RenameField(
            model_name='games',
            old_name='game_name',
            new_name='game_title',
        ),
        migrations.AddField(
            model_name='games',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='game_logos/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banner',
            field=models.ImageField(null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='penalty_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='login_session_token',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='achievements/')),
                ('awarded_to', models.ManyToManyField(blank=True, null=True, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vent_auth.games')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInterests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vent_auth.interests')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
