# Generated by Django 5.0.7 on 2024-10-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0010_interests_rename_usergames_favoritegames_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='penalty_point',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
