# Generated by Django 5.0.7 on 2024-11-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0011_alter_userprofile_penalty_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_notified', models.BooleanField(default=False)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userinterests',
            name='interests',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Interests',
        ),
    ]
