# Generated by Django 5.0.7 on 2024-12-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0012_waitlist_alter_userinterests_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='provider_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='signup_type',
            field=models.CharField(default='normal', max_length=32),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
