# Generated by Django 5.0.7 on 2026-03-22 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0018_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='team_privacy',
        ),
        migrations.AddField(
            model_name='teams',
            name='allow_membership_requests',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='description',
            field=models.TextField(default='Passionate gamer with a sharp eye for detail...'),
        ),
        migrations.AddField(
            model_name='teams',
            name='number_of_members',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teams',
            name='penalty_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teams',
            name='team_banner',
            field=models.ImageField(blank=True, null=True, upload_to='teams_banners/'),
        ),
        migrations.AddField(
            model_name='teams',
            name='team_logo',
            field=models.ImageField(blank=True, null=True, upload_to='teams_logos/'),
        ),
        migrations.AddField(
            model_name='users',
            name='login_session_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='social_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='state',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='tst',
            field=models.CharField(max_length=44, null=True),
        ),
        migrations.AlterField(
            model_name='adminaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vent_auth_teams', to='vent_auth.games'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='team_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vent_auth_created_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teams',
            name='team_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vent_auth_owned_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='users',
            name='signup_type',
            field=models.CharField(default='normal', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='UserGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
