# Generated by Django 5.0.7 on 2026-07-06 20:45
# Adds the RBAC admin_role field + backfills existing staff to super_admin so
# no current admin is locked out when the decorator starts enforcing roles.

from django.db import migrations, models


def backfill_super_admin(apps, schema_editor):
    Users = apps.get_model('vent_auth', 'Users')
    Users.objects.filter(is_staff=True).update(admin_role='super_admin')


def clear_admin_role(apps, schema_editor):
    Users = apps.get_model('vent_auth', 'Users')
    Users.objects.update(admin_role=None)


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0020_transaction_reference_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='admin_role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('finance_admin', 'Finance Admin'), ('mod_admin', 'Moderator Admin'), ('support_admin', 'Support Admin')], max_length=32, null=True),
        ),
        migrations.RunPython(backfill_super_admin, clear_admin_role),
    ]
