# Generated by Django 5.0.7 on 2026-07-10 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


VALID_ROLES = {'owner', 'captain', 'vice_captain', 'member', 'coach', 'manager', 'analyst'}


def upsert_team_members(apps, schema_editor):
    """Consolidate GameAccount-based vent_team.TeamMembers → user-based
    vent_auth.TeamMembers (teams-consolidation Part A §5.3).

    No-op on an empty DB. ORM-only (no schema_editor DDL). Runs AFTER the
    AddField(role) operation above, so the vent_auth.TeamMembers historical
    model already exposes `role`/`is_captain`.
    """
    GameTeamMembers = apps.get_model('vent_team', 'TeamMembers')
    AuthTeamMembers = apps.get_model('vent_auth', 'TeamMembers')

    for gm in GameTeamMembers.objects.select_related('member').all():
        role = gm.role if gm.role in VALID_ROLES else 'member'
        obj, created = AuthTeamMembers.objects.get_or_create(
            team_id=gm.team_id,
            user_id=gm.member.user_id,
            defaults={'role': role, 'is_captain': role in ('owner', 'captain')},
        )
        # If a bare user-based row already existed, upgrade it to the richer role.
        if not created and (obj.role in (None, '', 'member')) and role != 'member':
            obj.role = role
            obj.is_captain = role in ('owner', 'captain')
            obj.save(update_fields=['role', 'is_captain'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0025_adminsetting'),
        # Needed so the historical vent_team.TeamMembers model is in state for
        # the RunPython data upsert below (read-source of the consolidation).
        ('vent_team', '0002_alter_teaminterests_team_alter_teammembers_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('captain', 'Captain'), ('vice_captain', 'Vice Captain'), ('member', 'Member'), ('coach', 'Coach'), ('manager', 'Manager'), ('analyst', 'Analyst')], default='member', max_length=20),
        ),
        migrations.AddField(
            model_name='teams',
            name='join_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='max_members',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='password_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TeamJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_join_requests', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='vent_auth.teams')),
            ],
        ),
        # Data upsert LAST — runs after role/columns exist. ORM-only, no DDL.
        migrations.RunPython(upsert_team_members, noop),
    ]
