# Generated by Django 5.0.7 on 2026-08-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0032_alter_thread_options_thread_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrim',
            name='match_format',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='scrim',
            name='region',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
