# Generated by Django 5.0.7 on 2026-08-17 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0033_scrim_match_format_scrim_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrim',
            name='challenged',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrims_challenged', to='vent_auth.teams'),
        ),
    ]
