# Generated by Django 5.0.7 on 2026-08-17 17:33

import vent_auth.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0034_scrim_challenged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='document_image',
            field=models.ImageField(storage=vent_auth.storages.private_storage, upload_to='kyc/'),
        ),
    ]
