# Generated by Django 5.0.7 on 2026-08-18 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0035_alter_kycdocument_document_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='founding_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_founding_member',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WaitlistReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('display_name', models.CharField(blank=True, max_length=148)),
                ('game', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('position', models.IntegerField(default=0)),
                ('referral_code', models.CharField(blank=True, max_length=32)),
                ('boost_count', models.IntegerField(default=0)),
                ('email_verified', models.BooleanField(default=False)),
                ('source_id', models.BigIntegerField(blank=True, null=True)),
                ('claim_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('claim_sent_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_reservation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
