# Generated by Django 5.0.7 on 2026-08-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0036_users_founding_position_users_is_founding_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationtoken',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verificationtoken',
            name='reset_ticket',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='verificationtoken',
            name='ticket_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
