# Generated by Django 5.0.7 on 2026-08-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0037_verificationtoken_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
