# Generated by Django 5.0.7 on 2026-08-25 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0038_users_last_login_ip_users_location_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritegames',
            name='gamertag',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='favoritegames',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PlatformAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=32)),
                ('display_name', models.CharField(blank=True, default='', max_length=64)),
                ('gamertag', models.CharField(blank=True, default='', max_length=64)),
                ('connected', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'platform')},
            },
        ),
    ]
