# Generated by Django 5.0.7 on 2026-08-25 23:47

from django.db import migrations, models


PLACEHOLDER = 'Passionate gamer with a sharp eye for detail...'


def clear_placeholder(apps, schema_editor):
    """Teams already carrying the old default are not describing themselves.

    Only the exact string is cleared, so a team that genuinely typed something
    is left alone.
    """
    Teams = apps.get_model('vent_auth', 'Teams')
    Teams.objects.filter(description=PLACEHOLDER).update(description='')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0040_loginevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(clear_placeholder, noop),
    ]
