# Generated by Django 5.0.7 on 2026-08-26 01:08

from django.db import migrations, models


FOUNDERS = ('layott', 'ladilawalt', 'winlola')


def mark_founders(apps, schema_editor):
    """The two people who founded V-ENT, by username.

    Matched case-insensitively because a handle is the same handle whatever the
    case, and `ladilawalt` is included because that is the account `Layott`
    actually signs in with.
    """
    Users = apps.get_model('vent_auth', 'Users')
    for username in FOUNDERS:
        Users.objects.filter(username__iexact=username).update(is_founder=True)


def unmark_founders(apps, schema_editor):
    apps.get_model('vent_auth', 'Users').objects.update(is_founder=False)


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0043_users_deactivated_at_users_deletion_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_founder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='show_founder_badge',
            field=models.BooleanField(default=True),
        ),
            migrations.RunPython(mark_founders, unmark_founders),
    ]
