# Generated by Django 5.0.7 on 2026-08-26 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0044_users_is_founder_users_show_founder_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_code', models.CharField(blank=True, default='', max_length=128)),
                ('signature', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('brand', models.CharField(blank=True, default='', max_length=32)),
                ('last4', models.CharField(blank=True, default='', max_length=4)),
                ('exp_month', models.CharField(blank=True, default='', max_length=2)),
                ('exp_year', models.CharField(blank=True, default='', max_length=4)),
                ('bank', models.CharField(blank=True, default='', max_length=120)),
                ('channel', models.CharField(blank=True, default='card', max_length=32)),
                ('country', models.CharField(blank=True, default='', max_length=8)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_default', '-created_at'),
            },
        ),
    ]
