# Generated by Django 5.0.7 on 2026-08-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0045_savedcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlugHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(db_index=True, max_length=32)),
                ('entity_id', models.PositiveIntegerField()),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('retired_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'slug history',
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='vent_auth_s_entity__2422d0_idx')],
            },
        ),
    ]
