# Generated by Django 5.0.7 on 2026-08-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0048_backfill_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='admin_session_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='admin_session_token',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
    ]
