# Generated by Django 5.0.7 on 2026-08-27 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0049_users_admin_session_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'ordering': ['sort_order', 'game_title']},
        ),
        migrations.AddField(
            model_name='games',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='games',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GameSeries',
            fields=[
                ('series_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(blank=True, max_length=160, null=True, unique=True)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='vent_auth.games')),
            ],
            options={
                'verbose_name_plural': 'Game series',
                'ordering': ['sort_order', '-release_year', 'name'],
                'unique_together': {('game', 'name')},
            },
        ),
    ]
