# Generated by Django 5.0.7 on 2026-08-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0052_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='login_session_2fa_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
