# Generated by Django 5.0.7 on 2026-08-27 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0054_one_second_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('mode_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('team_size', models.PositiveIntegerField(default=0)),
                ('default_format', models.CharField(blank=True, default='', max_length=40)),
                ('default_placement_table', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modes', to='vent_auth.games')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modes', to='vent_auth.gameseries')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('game', 'name')},
            },
        ),
    ]
