# Generated by Django 5.0.7 on 2026-08-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0056_seed_games_and_modes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gamemode',
            unique_together={('game', 'series', 'name')},
        ),
    ]
