# Generated by Django 5.0.7 on 2026-08-29 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def region_to_country(apps, schema_editor):
    """Carry across the region values that name a country, and only those.

    The old list mixed three vocabularies in one picker: Nigerian zones
    ('NG-West'), ISO country codes ('ZA', 'KE') and continental shards
    ('EU-West', 'NA-East', 'AS-East'). Only some of those answer the question
    "which country", so only those are carried.

    A continental shard is left blank on purpose. Guessing a country from
    'EU-West' would put a made-up fact in a field the rest of the platform
    compares against, and a blank is honestly empty where a wrong country is
    quietly wrong.
    """
    Scrim = apps.get_model('vent_auth', 'Scrim')
    known = {
        'NG-West': 'Nigeria',
        'NG-East': 'Nigeria',
        'NG-North': 'Nigeria',
        'NG-South': 'Nigeria',
        'NG': 'Nigeria',
        'ZA': 'South Africa',
        'KE': 'Kenya',
        'GH': 'Ghana',
        'EG': 'Egypt',
    }
    for scrim in Scrim.objects.exclude(region='').only('id', 'region'):
        country = known.get((scrim.region or '').strip(), '')
        if country:
            Scrim.objects.filter(pk=scrim.pk).update(country=country)


def country_to_region(apps, schema_editor):
    """Backwards: the old column comes back empty.

    There is no honest reverse. 'Nigeria' could have been any of four zones
    and the row no longer records which, so inventing one would be worse than
    an empty cell.
    """
    return None



class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0058_conversation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrim',
            name='challenged_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrims_challenged_solo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scrim',
            name='country',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='scrim',
            name='map_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='scrim',
            name='mode',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='scrim',
            name='opponent_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrims_accepted_solo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scrim',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrims_as_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scrim',
            name='team_size',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='scrim',
            name='match_format',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='scrim',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrims_posted', to='vent_auth.teams'),
        ),
        # Carry what can be carried, THEN drop the column. The other order
        # loses the values before anything can read them.
        migrations.RunPython(region_to_country, country_to_region),
        migrations.RemoveField(
            model_name='scrim',
            name='region',
        ),
    ]
