# Generated by Django 5.0.7 on 2026-08-29 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0059_remove_scrim_region_scrim_challenged_player_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInvite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('direct', 'To one player'), ('link', 'A link anyone may use')], default='direct', max_length=10)),
                ('role', models.CharField(default='member', max_length=20)),
                ('message', models.CharField(blank=True, default='', max_length=280)),
                ('token', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(default=0)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Waiting for an answer'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('revoked', 'Withdrawn')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='vent_auth.teams')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_invites_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='teaminvite',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'direct'), ('status', 'pending')), fields=('team', 'user'), name='one_pending_direct_team_invite'),
        ),
    ]
