# Generated by Django 5.0.7 on 2026-08-29 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0060_teaminvite_teaminvite_one_pending_direct_team_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrimResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score_a', models.IntegerField(default=0)),
                ('score_b', models.IntegerField(default=0)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('reported', 'Waiting to be confirmed'), ('confirmed', 'Agreed by both sides'), ('disputed', 'The two sides disagree')], default='reported', max_length=20)),
                ('disputed_score_a', models.IntegerField(blank=True, null=True)),
                ('disputed_score_b', models.IntegerField(blank=True, null=True)),
                ('disputed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=280)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrim_results_confirmed', to=settings.AUTH_USER_MODEL)),
                ('disputed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrim_results_disputed', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrim_results_reported', to=settings.AUTH_USER_MODEL)),
                ('scrim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='vent_auth.scrim')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
