# Generated by Django 5.0.7 on 2026-08-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0061_scrimresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrim',
            name='countries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scrim',
            name='open_to',
            field=models.CharField(choices=[('anywhere', 'Anyone, anywhere'), ('countries', 'A chosen group of countries'), ('country', 'One country')], default='country', max_length=20),
        ),
    ]
