# Generated by Django 5.0.7 on 2026-08-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0065_club_organization_orgmember_scopes_orginvite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergallery',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='usergallery',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='usergallery',
            name='kind',
            field=models.CharField(choices=[('personal', 'Personal'), ('esports', 'Esports')], default='personal', max_length=16),
        ),
        migrations.AddField(
            model_name='usergallery',
            name='release_terms_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='usergallery',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
