# Generated by Django 5.0.7 on 2026-08-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0066_alter_usergallery_options_usergallery_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='country_is_guess',
            field=models.BooleanField(default=False),
        ),
    ]
