# Generated by Django 5.0.7 on 2026-08-31 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0067_users_country_is_guess'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPLocation',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, default='', max_length=120)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('source', models.CharField(blank=True, default='', max_length=20)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
