# Generated by Django 5.0.7 on 2026-09-06 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0069_userblock_usermute_userreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('area', models.CharField(choices=[('tournaments', 'Tournaments'), ('events', 'Events and tickets'), ('door', 'Check-in and the door'), ('studio', 'Production and streaming'), ('teams', 'Teams and squads'), ('wallet', 'Wallet and payments'), ('community', 'Community'), ('pricing', 'Pricing'), ('other', 'Something else')], default='other', max_length=20)),
                ('kind', models.CharField(choices=[('broken', 'Something is broken'), ('confusing', 'Something is confusing'), ('missing', 'Something is missing'), ('praise', 'Something works well')], default='broken', max_length=20)),
                ('message', models.TextField()),
                ('page', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('handled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
