# Generated by Django 5.0.7 on 2026-09-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0070_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformaccount',
            name='dm_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='dm_error',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='dm_last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='provider_user_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
