# Generated by Django 5.0.7 on 2026-09-07 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0071_platform_account_discord_id'),
        ('vent_event', '0034_doorlookup_kind'),
        ('vent_tournament', '0048_broadcastslot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordWebhook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=300)),
                ('label', models.CharField(blank=True, default='', max_length=80)),
                ('events', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_ok_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=200)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discord_webhooks', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discord_webhooks', to='vent_event.event')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discord_webhooks', to='vent_tournament.tournament')),
            ],
            options={
                'indexes': [models.Index(fields=['tournament', 'active'], name='vent_auth_d_tournam_a5528b_idx'), models.Index(fields=['event', 'active'], name='vent_auth_d_event_i_8bfd84_idx')],
            },
        ),
    ]
