# Generated by Django 5.0.7 on 2026-09-07 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0072_discord_webhook'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordServer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guild_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('guild_name', models.CharField(blank=True, default='', max_length=120)),
                ('icon', models.CharField(blank=True, default='', max_length=200)),
                ('granted', models.JSONField(blank=True, default=list)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('live_permissions', models.BigIntegerField(default=0)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discord_servers_connected', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discord_servers', to='vent_auth.organization')),
            ],
        ),
        migrations.CreateModel(
            name='DiscordAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=32)),
                ('target', models.CharField(blank=True, default='', max_length=120)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ok', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, default='', max_length=200)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discord_actions', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='vent_auth.discordserver')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.AddIndex(
            model_name='discordserver',
            index=models.Index(fields=['org', 'active'], name='vent_auth_d_org_id_5502c8_idx'),
        ),
        migrations.AddIndex(
            model_name='discordaction',
            index=models.Index(fields=['server', '-at'], name='vent_auth_d_server__ef0f7e_idx'),
        ),
    ]
