# Generated by Django 5.0.7 on 2026-09-07 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0073_discord_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('team', 'Team or club'), ('esports', 'Esports organisation'), ('events', 'Event organiser'), ('brand', 'Brand or sponsor'), ('community', 'Community or fan group'), ('mixed', 'A bit of everything')], default='mixed', max_length=20),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('team', 'Team'), ('user', 'Person')], max_length=10)),
                ('target_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'target_id'], name='vent_auth_f_kind_098524_idx')],
                'unique_together': {('follower', 'kind', 'target_id')},
            },
        ),
    ]
