"""Invites gain an email, and can be addressed to somebody with no account.

CEO, 7 September 2026: "you should be able to type in peoples emails and it
shows users or just even people who dont have accounts and they receive invites
to the website and to the org."

The column alone is half of it. Every invite that already exists was addressed
to a USER, and leaving its email blank would mean the claim-on-signup path
could never match it - so an existing invitation to somebody who then changes
their address, or an admin looking for "who did we invite", finds nothing.
Backfilled from the account it points at.
"""
# Generated by Django 5.0.7 on 2026-09-07 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def fill_emails(apps, schema_editor):
    for name in ('OrgInvite', 'TeamInvite'):
        model = apps.get_model('vent_auth', name)
        for row in model.objects.filter(email='').exclude(user__isnull=True):
            row.email = (row.user.email or '').lower()
            if row.email:
                row.save(update_fields=['email'])


def clear_emails(apps, schema_editor):
    for name in ('OrgInvite', 'TeamInvite'):
        apps.get_model('vent_auth', name).objects.update(email='')


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0074_organization_org_type_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='orginvite',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='teaminvite',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='orginvite',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(fill_emails, clear_emails),
    ]
