# Generated by Django 5.0.7 on 2026-09-07 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0075_orginvite_email_teaminvite_email_and_more'),
        ('vent_tournament', '0048_broadcastslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgwallet',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='teamwallet',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='org_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='vent_auth.orgwallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='team_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='vent_auth.teamwallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('top_up', 'Top Up'), ('deduction', 'Deduction'), ('prize', 'Prize'), ('send', 'Send'), ('receive', 'Receive'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund'), ('transfer', 'Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='vent_auth.userwallet'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('org_wallet__isnull', True), ('team_wallet__isnull', True), ('wallet__isnull', False)), models.Q(('org_wallet__isnull', True), ('team_wallet__isnull', False), ('wallet__isnull', True)), models.Q(('org_wallet__isnull', False), ('team_wallet__isnull', True), ('wallet__isnull', True)), _connector='OR'), name='transaction_has_exactly_one_wallet'),
        ),
    ]
