# Generated by Django 5.0.7 on 2026-09-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0076_orgwallet_pin_hash_teamwallet_pin_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='admin_role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('finance_admin', 'Financial Manager'), ('mod_admin', 'Moderator'), ('tournament_admin', 'Tournament Organizer'), ('marketplace_admin', 'Marketplace Manager'), ('wager_admin', 'Wager Manager'), ('support_admin', 'Support Admin')], max_length=32, null=True),
        ),
    ]
