# Generated by Django 5.0.7 on 2026-09-08 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0077_alter_users_admin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdocument',
            name='provider',
            field=models.CharField(default='in_house', max_length=40),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='provider_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='hold',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_request', to='vent_auth.transaction'),
        ),
    ]
