# Generated by Django 5.0.7 on 2026-09-08 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0078_kycdocument_provider_kycdocument_provider_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='method',
            field=models.CharField(choices=[('bank', 'Bank transfer'), ('usdt', 'USDT')], default='bank', max_length=10),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payout_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='account_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='PayoutAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('trc20', 'USDT on TRON (TRC-20)'), ('erc20', 'USDT on Ethereum (ERC-20)')], default='trc20', max_length=10)),
                ('address', models.CharField(max_length=128)),
                ('label', models.CharField(blank=True, default='', max_length=60)),
                ('ref', models.CharField(blank=True, max_length=24, unique=True)),
                ('confirm_code', models.CharField(blank=True, default='', max_length=12)),
                ('confirm_sent_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'network', 'address')},
            },
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payout_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='vent_auth.payoutaddress'),
        ),
    ]
