# Generated by Django 5.0.7 on 2026-09-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0079_withdrawalrequest_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='premium_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='users',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='premium_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
