# Generated by Django 5.0.7 on 2026-09-09 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0080_organization_is_premium_organization_premium_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PremiumInterest',
            fields=[
                ('interest_id', models.AutoField(primary_key=True, serialize=False)),
                ('surface', models.CharField(blank=True, default='', max_length=60)),
                ('times', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_interest', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_at'],
            },
        ),
        migrations.CreateModel(
            name='PremiumPurchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('coins', models.IntegerField()),
                ('months', models.PositiveSmallIntegerField(default=1)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_purchases', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premium_purchases', to='vent_auth.organization')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premium_purchases', to='vent_auth.transaction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premium_bought_for', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['buyer', '-created_at'], name='vent_auth_p_buyer_i_0d5b28_idx'), models.Index(fields=['period_end'], name='vent_auth_p_period__c18de0_idx')],
            },
        ),
    ]
