"""What comes off a payout, stamped on the request when it is asked for.

Rows made before this carry 0 everywhere, and `views_admin._payout_ngn` reads
an unstamped row as worth its coins in full, which is what was always sent.
CEO, 13 September 2026: every platform rate is set on the admin dashboard.
"""
# Generated by Django 5.0.7 on 2026-09-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0081_organization_premium_until_users_premium_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='fee_flat_ngn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='fee_ngn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='fee_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payout_ngn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
