# Generated by Django 5.2.17 on 2026-09-30 01:41

import vent_auth.storages
import vent_auth.uploads
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0084_notification_switches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='awarded_to',
            field=models.ManyToManyField(blank=True, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=vent_auth.uploads.OpaqueName('achievements/')),
        ),
        migrations.AlterField(
            model_name='club',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=vent_auth.uploads.OpaqueName('club_banners/')),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=vent_auth.uploads.OpaqueName('club_logos/')),
        ),
        migrations.AlterField(
            model_name='games',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=vent_auth.uploads.OpaqueName('game_logos/')),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='document_image',
            field=models.ImageField(storage=vent_auth.storages.private_storage, upload_to=vent_auth.uploads.OpaqueName('kyc/')),
        ),
        migrations.AlterField(
            model_name='organization',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=vent_auth.uploads.OpaqueName('org_banners/')),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=vent_auth.uploads.OpaqueName('org_logos/')),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=vent_auth.uploads.OpaqueName('post_images/')),
        ),
        migrations.AlterField(
            model_name='teams',
            name='team_banner',
            field=models.ImageField(blank=True, null=True, upload_to=vent_auth.uploads.OpaqueName('teams_banners/')),
        ),
        migrations.AlterField(
            model_name='teams',
            name='team_logo',
            field=models.ImageField(blank=True, null=True, upload_to=vent_auth.uploads.OpaqueName('teams_logos/')),
        ),
        migrations.AlterField(
            model_name='usergallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=vent_auth.uploads.OpaqueName('gallery/')),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='banner',
            field=models.ImageField(null=True, upload_to=vent_auth.uploads.OpaqueName('banners/')),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=vent_auth.uploads.OpaqueName('profile_pictures/')),
        ),
    ]
