# Generated by Django 5.2.17 on 2026-09-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0085_alter_achievement_awarded_to_alter_achievement_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
