# Generated by Django 5.2.17 on 2026-09-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0086_usedchallenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('rate', models.DecimalField(decimal_places=6, help_text="NGN per one unit of the currency, Flutterwave's figure at the time", max_digits=18)),
                ('amount_ngn', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
