# Generated by Django 5.2.17 on 2026-09-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0087_foreigncharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgwallet',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='teamwallet',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
