# Generated by Django 5.0.7 on 2026-10-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0088_coins_in_hundredths'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformaccount',
            name='avatar_url',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
