# Generated by Django 5.0.7 on 2026-10-09 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_auth', '0090_module_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=100)),
                ('object_pk', models.CharField(max_length=64)),
                ('label', models.CharField(blank=True, default='', max_length=160)),
                ('counts', models.JSONField(default=dict)),
                ('snapshot', models.JSONField(default=dict)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('purge_after', models.DateTimeField(db_index=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(db_index=True, max_length=100)),
                ('object_pk', models.CharField(db_index=True, max_length=64)),
                ('label', models.CharField(blank=True, default='', max_length=160)),
                ('changes', models.JSONField(default=dict)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reverts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_by', to='vent_auth.recordversion')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
