"""
Django settings for vent project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
import pymysql
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()

pymysql.version_info = (1, 4, 6, 'final', 0)
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Fail loudly rather than booting production on a missing/dev key.
if not DEBUG and (not SECRET_KEY or SECRET_KEY.startswith('django-insecure-')):
    raise ImproperlyConfigured(
        'SECRET_KEY must be set to a real value when DEBUG is off. '
        'Generate one with: python -c "from django.core.management.utils import '
        'get_random_secret_key as k; print(k())"'
    )


# Public uploads (avatars, banners, logos). nginx serves this directory directly.
MEDIA_URL = '/media/'
MEDIA_ROOT = os.environ.get('MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))

# Private uploads (KYC identity documents). NEVER served by nginx directly - see
# vent_auth/storages.py and the kyc_document view. Kept outside MEDIA_ROOT so a
# misconfigured `location /media/` block can never expose a government ID.
PRIVATE_MEDIA_ROOT = os.environ.get('PRIVATE_MEDIA_ROOT', os.path.join(BASE_DIR, 'private'))
# The nginx `internal` location that fronts PRIVATE_MEDIA_ROOT for X-Accel-Redirect.
PRIVATE_MEDIA_URL = os.environ.get('PRIVATE_MEDIA_URL', '/private/')

# Local IP-to-location database (DB-IP City Lite, MaxMind format). Used to fill
# a new account's country and region without asking for them at signup and
# without calling out to a geolocation service. Absent = the lookup is skipped.
GEOIP_DB_PATH = os.environ.get('GEOIP_DB_PATH', os.path.join(BASE_DIR, 'geo', 'dbip-city-lite.mmdb'))

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "vent_auth",
    "vent_anime",
    "vent_marketplace",
    "vent_tournament",
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'rest_framework',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'rest_framework.authtoken',
    'corsheaders',
    'vent_event',
    'vent_team'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'allauth.account.middleware.AccountMiddleware',
]

CORS_ALLOW_CREDENTIALS = True

# Local dev origins are always allowed; production hosts come from the env so a
# deploy never depends on editing this file. Set CORS_ALLOWED_ORIGINS and
# CSRF_TRUSTED_ORIGINS as comma-separated absolute origins (scheme included).
_DEV_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    # Alt dev ports (used when 3000 is occupied by another local project)
    "http://localhost:3100",
    "http://127.0.0.1:3100",
]


def _origins(env_name):
    raw = os.environ.get(env_name, '')
    extra = [o.strip() for o in raw.split(',') if o.strip()]
    return extra + (_DEV_ORIGINS if DEBUG else [])


CORS_ALLOWED_ORIGINS = _origins('CORS_ALLOWED_ORIGINS')
CSRF_TRUSTED_ORIGINS = _origins('CSRF_TRUSTED_ORIGINS')

SITE_ID = 1

ROOT_URLCONF = "vent.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "vent.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'vent'),
        'USER': os.environ.get('DB_USER', 'admin'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        # Reuse connections instead of a fresh MySQL handshake per request.
        # 0 in dev so the runserver autoreloader never holds a stale socket.
        'CONN_MAX_AGE': 0 if DEBUG else int(os.environ.get('CONN_MAX_AGE', '60')),
        'CONN_HEALTH_CHECKS': not DEBUG,
        'OPTIONS': {'charset': 'utf8mb4'},
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = 'vent_auth.Users'

AUTHENTICATION_BACKENDS = (
    'vent_auth.backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
# collectstatic target. nginx serves this directory at /static/ in production;
# without it `collectstatic` fails and the Django admin renders unstyled.
STATIC_ROOT = os.environ.get('STATIC_ROOT', os.path.join(BASE_DIR, 'staticfiles'))


# ---------------------------------------------------------------------------
# Production hardening. Every flag here is a no-op in local development
# (DEBUG=True) so the dev loop over plain http keeps working unchanged.
# ---------------------------------------------------------------------------
if not DEBUG:
    # nginx terminates TLS and forwards the original scheme.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True

    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True

    SECURE_HSTS_SECONDS = 31536000          # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    X_FRAME_OPTIONS = 'DENY'

    # Uploads land in a private directory owned by the app user only.
    FILE_UPLOAD_PERMISSIONS = 0o640

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# settings.py

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID'),
            'secret': os.environ.get('GOOGLE_CLIENT_SECRET'),
            'key': '',
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'offline'},
    }
}

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Email Backend
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# SMTP Configuration
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_ADDRESS')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASSWORD')

FRONTEND_URL = os.environ.get('FRONTEND_URL', 'https://test.app.v-ent.co')
FRONTEND_LOCALHOST = os.environ.get('FRONTEND_LOCALHOST', 'http://localhost:3000')