from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # path("admin/", admin.site.urls),
    path('signup/', signup, name='signup'),
    path('verify/<uidb64>/<token>/', verify_token_3, name='verify_token_3'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('dj-rest-auth/', include('dj_rest_auth.urls')),
    path('dj-rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    path('accounts/', include('allauth.urls')),
    path('dj-rest-auth/google/', GoogleLogin.as_view(), name='google_login'),
    path('change-fullname/', change_fullname, name='change_fullname'),
    path('change-email/', change_email, name='change_email'),
    path('verify-new-email/', verify_new_email, name='verify_new_email'),
    path('verify-token-2/', verify_token_2, name='verify_token_2'),
    path("forgot-password/send-token/", forgot_password, name="forgot_password"),
    path("forgot-password/verify-token/", verify_forgot_password_token, name="verify_forgot_password_token"),
    path("forgot-password/change-password/", change_password_fp, name="change_password_fp"),
    path("send-code/", send_code, name="send_code"),
    path("save-username/", save_username, name="save_username"),
    path("admin/login/", admin_login, name="admin_login"),
    path("admin/get-all-username-and-email/", get_all_username_and_email, name="get_all_username_and_email"),
    path("admin/user-count/", get_number_of_all_users, name="get_number_of_all_users"),
    path("admin/check-username-availability/", check_username_availability, name="check_username_availability"),
    # Admin dashboard
    path("admin/metrics/", admin_metrics, name="admin_metrics"),
    path("admin/users/", admin_list_users, name="admin_list_users"),
    path("admin/users/<int:user_id>/", admin_get_user, name="admin_get_user"),
    path("admin/users/<int:user_id>/ban/", admin_ban_user, name="admin_ban_user"),
    path("admin/users/<int:user_id>/role/", admin_set_user_role, name="admin_set_user_role"),
    path("admin/users/<int:user_id>/delete/", admin_delete_user, name="admin_delete_user"),
    path("admin/tournaments/", admin_list_tournaments, name="admin_list_tournaments"),
    path("admin/tournaments/<int:tournament_id>/", admin_get_tournament, name="admin_get_tournament"),
    path("admin/tournaments/<int:tournament_id>/dispute/resolve/", admin_resolve_dispute, name="admin_resolve_dispute"),
    path("admin/tournaments/<int:tournament_id>/cancel/", admin_cancel_tournament, name="admin_cancel_tournament"),
    path("admin/matches/<int:match_id>/score/", admin_override_match_score, name="admin_override_match_score"),
    path("admin/payouts/pending/", admin_pending_payouts, name="admin_pending_payouts"),
    path("admin/payouts/<int:withdrawal_id>/approve/", admin_approve_payout, name="admin_approve_payout"),
    path("admin/payouts/<int:withdrawal_id>/reject/", admin_reject_payout, name="admin_reject_payout"),
    path("admin/kyc/pending/", admin_pending_kyc, name="admin_pending_kyc"),
    path("admin/kyc/<int:kyc_id>/approve/", admin_approve_kyc, name="admin_approve_kyc"),
    path("admin/kyc/<int:kyc_id>/reject/", admin_reject_kyc, name="admin_reject_kyc"),
    path("get-username-with-email/", get_username_with_email, name="get_username_with_email"),
    path("edit-profile-info/", edit_profile_info, name="edit_profile_info"),
    path("get-user-informations/", get_user_informations, name="get_user_informations"),
    path("get-user-status/", get_user_status, name="get_user_status"),
    path("add-email-to-waitlist/", add_email_to_waitlist, name="add_email_to_waitlist"),
    path("update-web-and-social-links/", update_web_and_social_links, name="update_web_and_social_links"),
    path("social-auth/", social_auth, name="social_auth"),
    path("edit-favorite-games/", edit_favorite_games, name="edit_favorite_games"),
    path("resend-link/", resend_link, name="resend_link"),
    path("resend-forgot-password-token/", resend_forgot_password_token, name="resend_forgot_password_token"),
    path("get-google-login-url/", get_google_login_url, name="get_google_login_url"),
    path("google-callback/", google_callback, name="google_callback"),
    path("verify-google-token/", verify_token, name="verify_token"),
    path("upload-images/", upload_images, name="upload_images"),
    path("get-user-gallery/", get_user_gallery, name="get_user_gallery"),
    path("delete-gallery-image/", delete_gallery_image, name="delete_gallery_image"),
    # Wallet
    path("wallet/balance/", get_wallet_balance, name="get_wallet_balance"),
    path("wallet/transactions/", get_wallet_transactions, name="get_wallet_transactions"),
    path("wallet/topup/initiate/", topup_initiate, name="topup_initiate"),
    path("wallet/topup/verify/", topup_verify, name="topup_verify"),
    path("wallet/send/", send_funds, name="send_funds"),
    path("wallet/pin/verify/", verify_wallet_pin, name="verify_wallet_pin"),
    path("wallet/pin/set/", set_wallet_pin, name="set_wallet_pin"),
    path("wallet/deduct/", wallet_deduct, name="wallet_deduct"),
    path("wallet/withdraw/initiate/", withdraw_initiate, name="withdraw_initiate"),
    path("wallet/withdraw/status/", withdraw_status, name="withdraw_status"),
    path("wallet/kyc/submit/", kyc_submit, name="kyc_submit"),
    path("wallet/kyc/status/", kyc_status, name="kyc_status"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)