# Generated by Django 5.0.7 on 2026-09-03 21:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vent_tournament', '0039_squadmember_tournamentsquad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('futbin', 'Futbin'), ('manual', 'Entered by hand')], default='futbin', max_length=16)),
                ('source_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.CharField(db_index=True, max_length=140)),
                ('rating', models.PositiveSmallIntegerField()),
                ('position', models.CharField(max_length=8)),
                ('alt_positions', models.JSONField(blank=True, default=list)),
                ('club', models.CharField(blank=True, default='', max_length=120)),
                ('league', models.CharField(blank=True, default='', max_length=120)),
                ('nation', models.CharField(blank=True, default='', max_length=120)),
                ('nation_id', models.IntegerField(blank=True, null=True)),
                ('item_type', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('icon', 'Icon'), ('hero', 'Hero'), ('special', 'Special'), ('other', 'Other')], default='gold', max_length=16)),
                ('variant', models.CharField(blank=True, default='', max_length=64)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('weak_foot', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skill_moves', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price_coins', models.BigIntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('frame_url', models.URLField(blank=True, default='', max_length=500)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rating', 'name'],
                'indexes': [models.Index(fields=['slug'], name='vent_cards__slug_fefc5c_idx'), models.Index(fields=['rating'], name='vent_cards__rating_3f4f1b_idx'), models.Index(fields=['position'], name='vent_cards__positio_1f848c_idx')],
                'unique_together': {('source', 'source_id')},
            },
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('formation', models.CharField(default='4-3-3', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='vent_tournament.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
                'unique_together': {('tournament', 'user')},
            },
        ),
        migrations.CreateModel(
            name='LineupRules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('weekly_day', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('weekly_time', models.TimeField(blank=True, null=True)),
                ('changes_open_at', models.DateTimeField(blank=True, null=True)),
                ('changes_close_at', models.DateTimeField(blank=True, null=True)),
                ('changes_allowed', models.PositiveSmallIntegerField(default=1)),
                ('locked_by_hand', models.BooleanField(default=False)),
                ('reopened_by_hand', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_rules', to='vent_tournament.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='LineupSlot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_index', models.PositiveSmallIntegerField()),
                ('position', models.CharField(blank=True, default='', max_length=8)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_lineups', to='vent_cards.gamecard')),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='vent_cards.lineup')),
            ],
            options={
                'ordering': ['slot_index'],
                'unique_together': {('lineup', 'slot_index')},
            },
        ),
    ]
