# Generated by Django 5.0.7 on 2026-09-03 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_cards', '0001_initial'),
        ('vent_tournament', '0040_alter_broadcastelement_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='review_note',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
        migrations.AddField(
            model_name='lineup',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineup',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineups_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lineup',
            name='status',
            field=models.CharField(choices=[('draft', 'Still being built'), ('submitted', 'Submitted, waiting to be checked'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=12),
        ),
        migrations.CreateModel(
            name='SquadRules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('max_budget_coins', models.BigIntegerField(default=0)),
                ('required_nation', models.CharField(blank=True, default='', max_length=120)),
                ('min_from_nation', models.PositiveSmallIntegerField(default=0)),
                ('banned_item_types', models.JSONField(blank=True, default=list)),
                ('max_card_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='squad_rules', to='vent_tournament.tournament')),
            ],
        ),
    ]
